{{- if not .Values.global.development.minimalDeployment }}
{{- $baseName := regexReplaceAll "_" .Chart.Name "-" }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $baseName }}-internal-api
spec:
  type: NodePort
  selector:
    app: {{ $baseName }}-internal-api
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $baseName }}-internal-api
spec:
  selector:
    matchLabels:
      app: {{ $baseName }}-internal-api
  replicas: {{ .Values.internalApi.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    metadata:
      name: {{ $baseName }}-internal-api
      labels:
        app: {{ $baseName }}-internal-api
        product: semaphoreci
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
        - name: {{ . }}
{{- end }}
{{- end }}
      automountServiceAccountToken: false
      volumes:
        - name: features-volume
          configMap:
            defaultMode: 0644
            name: features
            items:
            - key: features.yml
              path: features.yml
      initContainers:
{{ include "initContainers.waitForPostgres" . | indent 8 }}
      containers:
        - name: {{ $baseName }}-internal-api
          image: "{{ .Values.global.image.registry }}/{{ .Values.image }}:{{ .Values.imageTag }}"
          ports:
            - name: grpc-port
              containerPort: 50051
          volumeMounts:
            - name: features-volume
              mountPath: "/home/front/app/features.yml"
              readOnly: true
              subPath: features.yml
          env:
            {{- include "env.db.go" . | indent 12 }}
            - name: FEATURE_YAML_PATH
              value: "/home/front/app/features.yml"
            - name: START_INTERNAL_API
              value: "yes"
            - name: DB_NAME
              value: self-hosted-hub
            - name: POSTGRES_DB_SSL
              value: {{ .Values.global.database.ssl | quote }}
            - name: DB_POOL_SIZE
              value: {{ .Values.internalApi.dbPoolSize | quote }}
            - name: APPLICATION_NAME
              value: "self-hosted-internal-api"
            - name: ON_PREM
              value: "true"

{{- if .Values.global.statsd.enabled }}
            - name: METRICS_NAMESPACE
              value: {{ .Values.global.statsd.metricsNamespace }}
{{- end }}
          startupProbe:
            grpc:
              port: 50051
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30
          livenessProbe:
            grpc:
              port: 50051
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
          readinessProbe:
            grpc:
              port: 50051
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
{{- if .Values.internalApi.resources }}
          resources:
{{ toYaml .Values.internalApi.resources | indent 13 }}
{{- end }}
{{- if .Values.global.statsd.enabled }}
        - name: {{ .Chart.Name }}-statsd
          image: "{{ .Values.global.image.registry }}/{{ .Values.global.statsd.image }}:{{ .Values.global.statsd.imageTag }}"
          env:
            - name: FLUSH_INTERVAL
              value: "60000"
            - name: GRAPHITE_HOST
              value: {{ .Values.global.statsd.graphiteHost }}
          resources:
            limits:
              cpu: "20m"
              memory: "50Mi"
            requests:
              cpu: "5m"
              memory: "25Mi"
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
{{- if .Values.statsd.resources }}
          resources:
{{ toYaml .Values.statsd.resources | indent 13 }}
{{- end }}
{{- end }}
{{- end }}
