services:
  app:
    container_name: hooks_processor
    image: ${IMAGE:-hooks_processor-app}:${TAG:-latest}
    build:
      context: .
      cache_from:
        - "${IMAGE:-hooks_processor}:${IMAGE_TAG:-latest}"
      dockerfile: Dockerfile
      target: ${DOCKER_BUILD_TARGET:-dev}
      args:
        - BUILD_ENV=test
      ssh:
        - default
    ports:
      - "50050"

    links:
      - db:db
      - rabbitmq:rabbitmq
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    environment:
      IN_DOCKER: "true"
      POSTGRES_DB_NAME: "front"
      POSTGRES_DB_USER: "postgres"
      POSTGRES_DB_PASSWORD: "the-cake-is-a-lie"
      POSTGRES_DB_HOST: "db"
      POSTGRES_DB_POOL_SIZE: 1
      AMQP_URL: "amqp://rabbitmq:5672"
      CI: $CI
      MIX_ENV: ${MIX_ENV:-dev}
      WEBHOOK_PROVIDER: "test"
      LOG_LEVEL: "debug"

    volumes:
      - .:/app
      - elixir_deps:/app/deps
      - elixir_build:/app/_build


  db:
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "the-cake-is-a-lie"
    restart: "on-failure"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.11.18-management
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error}]"
    restart: "on-failure"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  postgres-data:
    driver: local
  elixir_deps:
    driver: local
  elixir_build:
    driver: local
