# Generated by usvc-1.12.2
# Feel free to adjust, it will not be overridden

defmodule Ppl.Mixfile do
  use Mix.Project

  def project do
    [
      app: :ppl,
      version: "0.1.0",
      elixir: "~> 1.11",
      elixirc_paths: elixirc_paths(Mix.env()),
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      aliases: aliases()
    ]
  end

  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_), do: ["lib"]

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [
      extra_applications: extra_applications(Mix.env()),
      mod: {Ppl.Application, []}
    ]
  end

  defp extra_applications(:test), do: extra_applications(:default)

  defp extra_applications(_), do: [:logger]

  # Dependencies can be Hex packages:
  #
  #   {:my_dep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:my_dep, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [
      {:grpc, "~> 0.3"},
      {:log_tee, git: "https://github.com/renderedtext/log-tee.git"},
      {:uuid, "~> 1.1"},
      {:credo, "~> 1.4", only: [:dev, :test], runtime: false},
      {:poison, "~> 3.1"},
      {:httpoison, "~> 0.11"},
      # Pulled in transitively by httpoison; pinned forward to clear the hackney
      # CVEs (GHSA-9fm9-hp7p-53mf, GHSA-vq52-99r9-h5pw). 1.24 is the first
      # version patched against both. override needed because httpoison ~> 0.11
      # requests hackney ~> 1.8.
      {:hackney, "~> 1.24", override: true},
      {:mix_test_watch, "~> 1.1", only: :dev, runtime: false},
      {:mock, "~> 0.3.0", only: :test},
      {:ecto_sql, "~> 3.10"},
      {:postgrex, "~> 0.17"},
      {:jason, "~> 1.0"},
      {:scrivener_ecto, "~> 2.0"},
      {:paginator, "~> 1.0"},
      {:protobuf, "~> 0.5"},
      {:cachex, "~> 3.5"},
      {:definition_validator, path: "../definition_validator"},
      {:block, path: "../block"},
      {:job_matrix, path: "../job_matrix"},
      {:feature_provider, path: "../../feature_provider"},
      # feature_provider requests yaml_elixir >= 2.0, but plumber's
      # definition_validator (pipeline YAML validation) pins ~> 1.1. We only use
      # feature_provider's FeatureHub provider (not its YamlProvider), so pin the
      # existing 1.3 line to keep a single version across the umbrella.
      {:yaml_elixir, "~> 1.3", override: true},
      {:dialyxir, "~> 0.5", only: [:dev], runtime: false},
      {:amqp_client, "~> 3.9.2"},
      {:tackle, github: "renderedtext/ex-tackle", tag: "v0.2.1"},
      {:watchman, github: "renderedtext/ex-watchman"},
      {:looper, path: "../looper"},
      {:cloak, "~> 0.5.0"},
      {:vmstats, "~> 2.2"},
      {:observer_cli, "~> 1.7.1"},
      {:deep_merge, "~> 0.1.1"},
      {:proto, path: "../proto"},
      {:gofer_client, path: "../gofer_client"},
      {:when, github: "renderedtext/when"},
      {:grpc_mock, github: "renderedtext/grpc-mock", only: [:dev, :test]},
      {:ranch, "~> 1.6.2", override: true},
      {:jsx, "~> 2.9", override: true},
      {:timex, "~> 3.6"},
      {:junit_formatter, "~> 3.1", only: [:test]}
    ]
  end

  defp aliases() do
    [
      "deps.local": ["local.hex --force", "local.rebar --force"],
      "deps.setup": ["deps.local", "deps.get"],
      "ecto.reset": ["ecto.drop -r Ppl.EctoRepo -r Block.EctoRepo", "ecto.setup"],
      "ecto.setup": [
        "ecto.create -r Ppl.EctoRepo -r Block.EctoRepo",
        "ecto.migrate -r Ppl.EctoRepo -r Block.EctoRepo"
      ],
      setup: ["deps.setup", "ecto.setup"]
    ]
  end
end
