{{- if eq .Values.global.edition "ee" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "rbac-okta-http-api"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: "rbac-okta-http-api"
  replicas: {{ .Values.rbacEEOktaHttpApi.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    metadata:
      name: "rbac-okta-http-api"
      labels:
        app: "rbac-okta-http-api"
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
        - name: {{ . }}
{{- end }}
{{- end }}
      automountServiceAccountToken: false
      volumes:
        - name: features-volume
          configMap:
            defaultMode: 0644
            name: features
            items:
            - key: features.yml
              path: features.yml
        - name: roles-volume
          configMap:
            defaultMode: 0644
            name: roles
            items:
            - key: roles.yaml
              path: roles.yaml
        - name: permissions-volume
          configMap:
            defaultMode: 0644
            name: permissions
            items:
            - key: permissions.yaml
              path: permissions.yaml
      initContainers:
{{ include "initContainers.all" . | indent 8 }}
      priorityClassName: medium-priority
      containers:
        - name: "rbac-okta-http-api"
          image: "{{ .Values.global.image.registry }}/{{ .Values.image }}:{{ .Values.imageTag }}"
          command: ["bash", "-c"]
          args: ["bin/rbac start"]
          ports:
          - name: saml
            containerPort: 4001
          - name: scim
            containerPort: 4002
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: {{ .Values.global.internalApi.configMapName }}
            - configMapRef:
                name: {{ .Values.global.authentication.configMapName }}
            - secretRef:
                name: {{ include "secrets.authentication.name" . }}
          volumeMounts:
            - name: features-volume
              mountPath: "/app/features.yml"
              readOnly: true
              subPath: features.yml
            - name: roles-volume
              mountPath: "/app/assets/roles.yaml"
              readOnly: true
              subPath: roles.yaml
            - name: permissions-volume
              mountPath: "/app/assets/permissions.yaml"
              readOnly: true
              subPath: permissions.yaml
          env:
            {{- include "env.db.elixir" . | indent 12 }}
            - name: FEATURE_YAML_PATH
              value: "/app/features.yml"
            - name: START_GRPC_HEALTH_CHECK
              value: "true"
            - name: START_GRPC_RBAC_API
              value: "false"
            - name: START_GRPC_GROUPS_API
              value: "false"
            - name: START_GRPC_OKTA_API
              value: "false"
            - name: START_SAML_HTTP_API
              value: "true"
            - name: START_SCIM_HTTP_API
              value: "true"
            - name: START_RBAC_WORKERS
              value: "false"
            - name: RABBIT_CONSUMER
              value: "false"
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.rabbitmq.secretName }}
                  key: amqp-url
            - name: BASE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.domain.configMapName }}
                  key: BASE_DOMAIN
            - name: OIDC_DISCOVERY_URL
              value: "$(KC_ROOT_URL)/realms/$(KC_REALM)/.well-known/openid-configuration"
            - name: OIDC_MANAGE_URL
              value: "$(KC_LOCAL_URL)/admin/realms/$(KC_REALM)"
            - name: POSTGRES_DB_SSL
              value: {{ .Values.global.database.ssl | quote }}
            - name: POSTGRES_DB_NAME
              value: {{ .Values.db.name | quote }}
            - name: POSTGRES_FRONT_DB_NAME
              value: {{ .Values.db.frontName | quote }}
            - name: POSTGRES_DB_POOL_SIZE
              value: {{ .Values.rbacEEOktaHttpApi.dbPoolSize | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
{{- if .Values.global.statsd.enabled }}
            - name: METRICS_NAMESPACE
              value: {{ .Values.global.statsd.metricsNamespace }}
{{- end }}
          startupProbe:
            httpGet:
              path: /is_alive
              port: saml
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /is_alive
              port: saml
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
{{ toYaml .Values.rbacEEOktaHttpApi.resources | indent 12 }}
{{- if .Values.global.statsd.enabled }}
        - name: rbac-okta-http-api-statsd
          image: "{{ .Values.global.image.registry }}/{{ .Values.global.statsd.image }}:{{ .Values.global.statsd.imageTag }}"
          env:
            - name: FLUSH_INTERVAL
              value: "60000"
            - name: GRAPHITE_HOST
              value: {{ .Values.global.statsd.graphiteHost }}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
{{- if .Values.statsd.resources }}
          resources:
{{ toYaml .Values.statsd.resources | indent 13 }}
{{- end }}
{{- end }}
{{- end }}
