// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.3.0
// source: delivery.proto

package delivery

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Connection_Type int32

const (
	Connection_TYPE_UNKNOWN      Connection_Type = 0
	Connection_TYPE_EVENT_SOURCE Connection_Type = 1
	Connection_TYPE_STAGE        Connection_Type = 2
)

// Enum value maps for Connection_Type.
var (
	Connection_Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_EVENT_SOURCE",
		2: "TYPE_STAGE",
	}
	Connection_Type_value = map[string]int32{
		"TYPE_UNKNOWN":      0,
		"TYPE_EVENT_SOURCE": 1,
		"TYPE_STAGE":        2,
	}
)

func (x Connection_Type) Enum() *Connection_Type {
	p := new(Connection_Type)
	*p = x
	return p
}

func (x Connection_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Connection_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_proto_enumTypes[0].Descriptor()
}

func (Connection_Type) Type() protoreflect.EnumType {
	return &file_delivery_proto_enumTypes[0]
}

func (x Connection_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Connection_Type.Descriptor instead.
func (Connection_Type) EnumDescriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{12, 0}
}

type Connection_FilterType int32

const (
	Connection_FILTER_TYPE_UNKNOWN Connection_FilterType = 0
	Connection_FILTER_TYPE_DATA    Connection_FilterType = 1
)

// Enum value maps for Connection_FilterType.
var (
	Connection_FilterType_name = map[int32]string{
		0: "FILTER_TYPE_UNKNOWN",
		1: "FILTER_TYPE_DATA",
	}
	Connection_FilterType_value = map[string]int32{
		"FILTER_TYPE_UNKNOWN": 0,
		"FILTER_TYPE_DATA":    1,
	}
)

func (x Connection_FilterType) Enum() *Connection_FilterType {
	p := new(Connection_FilterType)
	*p = x
	return p
}

func (x Connection_FilterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Connection_FilterType) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_proto_enumTypes[1].Descriptor()
}

func (Connection_FilterType) Type() protoreflect.EnumType {
	return &file_delivery_proto_enumTypes[1]
}

func (x Connection_FilterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Connection_FilterType.Descriptor instead.
func (Connection_FilterType) EnumDescriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{12, 1}
}

// Filters can be combined in two ways:
//   - FILTER_OPERATOR_AND: all filters must be true (default)
//   - FILTER_OPERATOR_OR: at least one filter must be true
type Connection_FilterOperator int32

const (
	Connection_FILTER_OPERATOR_AND Connection_FilterOperator = 0
	Connection_FILTER_OPERATOR_OR  Connection_FilterOperator = 1
)

// Enum value maps for Connection_FilterOperator.
var (
	Connection_FilterOperator_name = map[int32]string{
		0: "FILTER_OPERATOR_AND",
		1: "FILTER_OPERATOR_OR",
	}
	Connection_FilterOperator_value = map[string]int32{
		"FILTER_OPERATOR_AND": 0,
		"FILTER_OPERATOR_OR":  1,
	}
)

func (x Connection_FilterOperator) Enum() *Connection_FilterOperator {
	p := new(Connection_FilterOperator)
	*p = x
	return p
}

func (x Connection_FilterOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Connection_FilterOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_proto_enumTypes[2].Descriptor()
}

func (Connection_FilterOperator) Type() protoreflect.EnumType {
	return &file_delivery_proto_enumTypes[2]
}

func (x Connection_FilterOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Connection_FilterOperator.Descriptor instead.
func (Connection_FilterOperator) EnumDescriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{12, 2}
}

type RunTemplate_Type int32

const (
	RunTemplate_TYPE_UNKNOWN   RunTemplate_Type = 0
	RunTemplate_TYPE_SEMAPHORE RunTemplate_Type = 1
)

// Enum value maps for RunTemplate_Type.
var (
	RunTemplate_Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_SEMAPHORE",
	}
	RunTemplate_Type_value = map[string]int32{
		"TYPE_UNKNOWN":   0,
		"TYPE_SEMAPHORE": 1,
	}
)

func (x RunTemplate_Type) Enum() *RunTemplate_Type {
	p := new(RunTemplate_Type)
	*p = x
	return p
}

func (x RunTemplate_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunTemplate_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_proto_enumTypes[3].Descriptor()
}

func (RunTemplate_Type) Type() protoreflect.EnumType {
	return &file_delivery_proto_enumTypes[3]
}

func (x RunTemplate_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunTemplate_Type.Descriptor instead.
func (RunTemplate_Type) EnumDescriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{15, 0}
}

type StageEvent_State int32

const (
	StageEvent_UNKNOWN                 StageEvent_State = 0
	StageEvent_PENDING                 StageEvent_State = 1
	StageEvent_WAITING_FOR_APPROVAL    StageEvent_State = 2
	StageEvent_WAITING_FOR_TIME_WINDOW StageEvent_State = 3
	StageEvent_PROCESSED               StageEvent_State = 4
)

// Enum value maps for StageEvent_State.
var (
	StageEvent_State_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "WAITING_FOR_APPROVAL",
		3: "WAITING_FOR_TIME_WINDOW",
		4: "PROCESSED",
	}
	StageEvent_State_value = map[string]int32{
		"UNKNOWN":                 0,
		"PENDING":                 1,
		"WAITING_FOR_APPROVAL":    2,
		"WAITING_FOR_TIME_WINDOW": 3,
		"PROCESSED":               4,
	}
)

func (x StageEvent_State) Enum() *StageEvent_State {
	p := new(StageEvent_State)
	*p = x
	return p
}

func (x StageEvent_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageEvent_State) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_proto_enumTypes[4].Descriptor()
}

func (StageEvent_State) Type() protoreflect.EnumType {
	return &file_delivery_proto_enumTypes[4]
}

func (x StageEvent_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StageEvent_State.Descriptor instead.
func (StageEvent_State) EnumDescriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{26, 0}
}

type Canvas struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Canvas) Reset() {
	*x = Canvas{}
	mi := &file_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Canvas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Canvas) ProtoMessage() {}

func (x *Canvas) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Canvas.ProtoReflect.Descriptor instead.
func (*Canvas) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *Canvas) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Canvas) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Canvas) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Canvas) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Canvas) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateCanvasRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	RequesterId    string                 `protobuf:"bytes,3,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCanvasRequest) Reset() {
	*x = CreateCanvasRequest{}
	mi := &file_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCanvasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCanvasRequest) ProtoMessage() {}

func (x *CreateCanvasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCanvasRequest.ProtoReflect.Descriptor instead.
func (*CreateCanvasRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCanvasRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCanvasRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateCanvasRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type CreateCanvasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Canvas        *Canvas                `protobuf:"bytes,1,opt,name=canvas,proto3" json:"canvas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCanvasResponse) Reset() {
	*x = CreateCanvasResponse{}
	mi := &file_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCanvasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCanvasResponse) ProtoMessage() {}

func (x *CreateCanvasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCanvasResponse.ProtoReflect.Descriptor instead.
func (*CreateCanvasResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCanvasResponse) GetCanvas() *Canvas {
	if x != nil {
		return x.Canvas
	}
	return nil
}

type DescribeCanvasRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DescribeCanvasRequest) Reset() {
	*x = DescribeCanvasRequest{}
	mi := &file_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCanvasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCanvasRequest) ProtoMessage() {}

func (x *DescribeCanvasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCanvasRequest.ProtoReflect.Descriptor instead.
func (*DescribeCanvasRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeCanvasRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DescribeCanvasRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeCanvasRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type DescribeCanvasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Canvas        *Canvas                `protobuf:"bytes,1,opt,name=canvas,proto3" json:"canvas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeCanvasResponse) Reset() {
	*x = DescribeCanvasResponse{}
	mi := &file_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCanvasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCanvasResponse) ProtoMessage() {}

func (x *DescribeCanvasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCanvasResponse.ProtoReflect.Descriptor instead.
func (*DescribeCanvasResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeCanvasResponse) GetCanvas() *Canvas {
	if x != nil {
		return x.Canvas
	}
	return nil
}

type EventSource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId       string                 `protobuf:"bytes,4,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventSource) Reset() {
	*x = EventSource{}
	mi := &file_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSource) ProtoMessage() {}

func (x *EventSource) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSource.ProtoReflect.Descriptor instead.
func (*EventSource) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *EventSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventSource) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *EventSource) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *EventSource) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DescribeStageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId       string                 `protobuf:"bytes,4,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DescribeStageRequest) Reset() {
	*x = DescribeStageRequest{}
	mi := &file_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeStageRequest) ProtoMessage() {}

func (x *DescribeStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeStageRequest.ProtoReflect.Descriptor instead.
func (*DescribeStageRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeStageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DescribeStageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeStageRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DescribeStageRequest) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

type DescribeStageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         *Stage                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeStageResponse) Reset() {
	*x = DescribeStageResponse{}
	mi := &file_delivery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeStageResponse) ProtoMessage() {}

func (x *DescribeStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeStageResponse.ProtoReflect.Descriptor instead.
func (*DescribeStageResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeStageResponse) GetStage() *Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

type CreateEventSourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId       string                 `protobuf:"bytes,3,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	RequesterId    string                 `protobuf:"bytes,4,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateEventSourceRequest) Reset() {
	*x = CreateEventSourceRequest{}
	mi := &file_delivery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventSourceRequest) ProtoMessage() {}

func (x *CreateEventSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventSourceRequest.ProtoReflect.Descriptor instead.
func (*CreateEventSourceRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{8}
}

func (x *CreateEventSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEventSourceRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateEventSourceRequest) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *CreateEventSourceRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type CreateEventSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventSource   *EventSource           `protobuf:"bytes,1,opt,name=event_source,json=eventSource,proto3" json:"event_source,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventSourceResponse) Reset() {
	*x = CreateEventSourceResponse{}
	mi := &file_delivery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventSourceResponse) ProtoMessage() {}

func (x *CreateEventSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventSourceResponse.ProtoReflect.Descriptor instead.
func (*CreateEventSourceResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{9}
}

func (x *CreateEventSourceResponse) GetEventSource() *EventSource {
	if x != nil {
		return x.EventSource
	}
	return nil
}

func (x *CreateEventSourceResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DescribeEventSourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId       string                 `protobuf:"bytes,4,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DescribeEventSourceRequest) Reset() {
	*x = DescribeEventSourceRequest{}
	mi := &file_delivery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeEventSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeEventSourceRequest) ProtoMessage() {}

func (x *DescribeEventSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeEventSourceRequest.ProtoReflect.Descriptor instead.
func (*DescribeEventSourceRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{10}
}

func (x *DescribeEventSourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DescribeEventSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeEventSourceRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DescribeEventSourceRequest) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

type DescribeEventSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventSource   *EventSource           `protobuf:"bytes,1,opt,name=event_source,json=eventSource,proto3" json:"event_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeEventSourceResponse) Reset() {
	*x = DescribeEventSourceResponse{}
	mi := &file_delivery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeEventSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeEventSourceResponse) ProtoMessage() {}

func (x *DescribeEventSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeEventSourceResponse.ProtoReflect.Descriptor instead.
func (*DescribeEventSourceResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{11}
}

func (x *DescribeEventSourceResponse) GetEventSource() *EventSource {
	if x != nil {
		return x.EventSource
	}
	return nil
}

type Connection struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Type           Connection_Type           `protobuf:"varint,1,opt,name=type,proto3,enum=InternalApi.Delivery.Connection_Type" json:"type,omitempty"`
	Name           string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Filters        []*Connection_Filter      `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	FilterOperator Connection_FilterOperator `protobuf:"varint,4,opt,name=filter_operator,json=filterOperator,proto3,enum=InternalApi.Delivery.Connection_FilterOperator" json:"filter_operator,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_delivery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{12}
}

func (x *Connection) GetType() Connection_Type {
	if x != nil {
		return x.Type
	}
	return Connection_TYPE_UNKNOWN
}

func (x *Connection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Connection) GetFilters() []*Connection_Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *Connection) GetFilterOperator() Connection_FilterOperator {
	if x != nil {
		return x.FilterOperator
	}
	return Connection_FILTER_OPERATOR_AND
}

type Stage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId         string                 `protobuf:"bytes,4,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	CreatedAt        *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Connections      []*Connection          `protobuf:"bytes,6,rep,name=connections,proto3" json:"connections,omitempty"`
	ApprovalRequired bool                   `protobuf:"varint,7,opt,name=approval_required,json=approvalRequired,proto3" json:"approval_required,omitempty"`
	RunTemplate      *RunTemplate           `protobuf:"bytes,8,opt,name=run_template,json=runTemplate,proto3" json:"run_template,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_delivery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{13}
}

func (x *Stage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Stage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stage) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Stage) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *Stage) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Stage) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *Stage) GetApprovalRequired() bool {
	if x != nil {
		return x.ApprovalRequired
	}
	return false
}

func (x *Stage) GetRunTemplate() *RunTemplate {
	if x != nil {
		return x.RunTemplate
	}
	return nil
}

type CreateStageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId         string                 `protobuf:"bytes,3,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	Connections      []*Connection          `protobuf:"bytes,4,rep,name=connections,proto3" json:"connections,omitempty"`
	ApprovalRequired bool                   `protobuf:"varint,5,opt,name=approval_required,json=approvalRequired,proto3" json:"approval_required,omitempty"`
	RequesterId      string                 `protobuf:"bytes,6,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	RunTemplate      *RunTemplate           `protobuf:"bytes,7,opt,name=run_template,json=runTemplate,proto3" json:"run_template,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateStageRequest) Reset() {
	*x = CreateStageRequest{}
	mi := &file_delivery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStageRequest) ProtoMessage() {}

func (x *CreateStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStageRequest.ProtoReflect.Descriptor instead.
func (*CreateStageRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{14}
}

func (x *CreateStageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStageRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateStageRequest) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *CreateStageRequest) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *CreateStageRequest) GetApprovalRequired() bool {
	if x != nil {
		return x.ApprovalRequired
	}
	return false
}

func (x *CreateStageRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *CreateStageRequest) GetRunTemplate() *RunTemplate {
	if x != nil {
		return x.RunTemplate
	}
	return nil
}

type RunTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RunTemplate_Type       `protobuf:"varint,1,opt,name=type,proto3,enum=InternalApi.Delivery.RunTemplate_Type" json:"type,omitempty"`
	Semaphore     *SemaphoreRunTemplate  `protobuf:"bytes,2,opt,name=semaphore,proto3" json:"semaphore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTemplate) Reset() {
	*x = RunTemplate{}
	mi := &file_delivery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTemplate) ProtoMessage() {}

func (x *RunTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTemplate.ProtoReflect.Descriptor instead.
func (*RunTemplate) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{15}
}

func (x *RunTemplate) GetType() RunTemplate_Type {
	if x != nil {
		return x.Type
	}
	return RunTemplate_TYPE_UNKNOWN
}

func (x *RunTemplate) GetSemaphore() *SemaphoreRunTemplate {
	if x != nil {
		return x.Semaphore
	}
	return nil
}

type SemaphoreRunTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	PipelineFile  string                 `protobuf:"bytes,3,opt,name=pipeline_file,json=pipelineFile,proto3" json:"pipeline_file,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemaphoreRunTemplate) Reset() {
	*x = SemaphoreRunTemplate{}
	mi := &file_delivery_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemaphoreRunTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemaphoreRunTemplate) ProtoMessage() {}

func (x *SemaphoreRunTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemaphoreRunTemplate.ProtoReflect.Descriptor instead.
func (*SemaphoreRunTemplate) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{16}
}

func (x *SemaphoreRunTemplate) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SemaphoreRunTemplate) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *SemaphoreRunTemplate) GetPipelineFile() string {
	if x != nil {
		return x.PipelineFile
	}
	return ""
}

func (x *SemaphoreRunTemplate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SemaphoreRunTemplate) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type CreateStageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         *Stage                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStageResponse) Reset() {
	*x = CreateStageResponse{}
	mi := &file_delivery_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStageResponse) ProtoMessage() {}

func (x *CreateStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStageResponse.ProtoReflect.Descriptor instead.
func (*CreateStageResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{17}
}

func (x *CreateStageResponse) GetStage() *Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

type UpdateStageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Connections   []*Connection          `protobuf:"bytes,2,rep,name=connections,proto3" json:"connections,omitempty"`
	RequesterId   string                 `protobuf:"bytes,3,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStageRequest) Reset() {
	*x = UpdateStageRequest{}
	mi := &file_delivery_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStageRequest) ProtoMessage() {}

func (x *UpdateStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStageRequest.ProtoReflect.Descriptor instead.
func (*UpdateStageRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateStageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStageRequest) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *UpdateStageRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type UpdateStageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         *Stage                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStageResponse) Reset() {
	*x = UpdateStageResponse{}
	mi := &file_delivery_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStageResponse) ProtoMessage() {}

func (x *UpdateStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStageResponse.ProtoReflect.Descriptor instead.
func (*UpdateStageResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateStageResponse) GetStage() *Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

type ListStagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId       string                 `protobuf:"bytes,2,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListStagesRequest) Reset() {
	*x = ListStagesRequest{}
	mi := &file_delivery_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStagesRequest) ProtoMessage() {}

func (x *ListStagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStagesRequest.ProtoReflect.Descriptor instead.
func (*ListStagesRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{20}
}

func (x *ListStagesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListStagesRequest) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

type ListStagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stages        []*Stage               `protobuf:"bytes,1,rep,name=stages,proto3" json:"stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStagesResponse) Reset() {
	*x = ListStagesResponse{}
	mi := &file_delivery_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStagesResponse) ProtoMessage() {}

func (x *ListStagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStagesResponse.ProtoReflect.Descriptor instead.
func (*ListStagesResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{21}
}

func (x *ListStagesResponse) GetStages() []*Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

type ListEventSourcesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId       string                 `protobuf:"bytes,2,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListEventSourcesRequest) Reset() {
	*x = ListEventSourcesRequest{}
	mi := &file_delivery_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventSourcesRequest) ProtoMessage() {}

func (x *ListEventSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListEventSourcesRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{22}
}

func (x *ListEventSourcesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListEventSourcesRequest) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

type ListEventSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventSources  []*EventSource         `protobuf:"bytes,1,rep,name=event_sources,json=eventSources,proto3" json:"event_sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventSourcesResponse) Reset() {
	*x = ListEventSourcesResponse{}
	mi := &file_delivery_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventSourcesResponse) ProtoMessage() {}

func (x *ListEventSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListEventSourcesResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{23}
}

func (x *ListEventSourcesResponse) GetEventSources() []*EventSource {
	if x != nil {
		return x.EventSources
	}
	return nil
}

type ListStageEventsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StageId        string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId       string                 `protobuf:"bytes,3,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	States         []StageEvent_State     `protobuf:"varint,4,rep,packed,name=states,proto3,enum=InternalApi.Delivery.StageEvent_State" json:"states,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListStageEventsRequest) Reset() {
	*x = ListStageEventsRequest{}
	mi := &file_delivery_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStageEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStageEventsRequest) ProtoMessage() {}

func (x *ListStageEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStageEventsRequest.ProtoReflect.Descriptor instead.
func (*ListStageEventsRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{24}
}

func (x *ListStageEventsRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *ListStageEventsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListStageEventsRequest) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *ListStageEventsRequest) GetStates() []StageEvent_State {
	if x != nil {
		return x.States
	}
	return nil
}

type ListStageEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*StageEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStageEventsResponse) Reset() {
	*x = ListStageEventsResponse{}
	mi := &file_delivery_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStageEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStageEventsResponse) ProtoMessage() {}

func (x *ListStageEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStageEventsResponse.ProtoReflect.Descriptor instead.
func (*ListStageEventsResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{25}
}

func (x *ListStageEventsResponse) GetEvents() []*StageEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type StageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceType    Connection_Type        `protobuf:"varint,3,opt,name=source_type,json=sourceType,proto3,enum=InternalApi.Delivery.Connection_Type" json:"source_type,omitempty"`
	State         StageEvent_State       `protobuf:"varint,4,opt,name=state,proto3,enum=InternalApi.Delivery.StageEvent_State" json:"state,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ApprovedAt    *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,7,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageEvent) Reset() {
	*x = StageEvent{}
	mi := &file_delivery_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageEvent) ProtoMessage() {}

func (x *StageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageEvent.ProtoReflect.Descriptor instead.
func (*StageEvent) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{26}
}

func (x *StageEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StageEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *StageEvent) GetSourceType() Connection_Type {
	if x != nil {
		return x.SourceType
	}
	return Connection_TYPE_UNKNOWN
}

func (x *StageEvent) GetState() StageEvent_State {
	if x != nil {
		return x.State
	}
	return StageEvent_UNKNOWN
}

func (x *StageEvent) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StageEvent) GetApprovedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

func (x *StageEvent) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

type ApproveStageEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StageId        string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId       string                 `protobuf:"bytes,3,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	EventId        string                 `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RequesterId    string                 `protobuf:"bytes,5,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApproveStageEventRequest) Reset() {
	*x = ApproveStageEventRequest{}
	mi := &file_delivery_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveStageEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveStageEventRequest) ProtoMessage() {}

func (x *ApproveStageEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveStageEventRequest.ProtoReflect.Descriptor instead.
func (*ApproveStageEventRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{27}
}

func (x *ApproveStageEventRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *ApproveStageEventRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ApproveStageEventRequest) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *ApproveStageEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ApproveStageEventRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type ApproveStageEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *StageEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveStageEventResponse) Reset() {
	*x = ApproveStageEventResponse{}
	mi := &file_delivery_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveStageEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveStageEventResponse) ProtoMessage() {}

func (x *ApproveStageEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveStageEventResponse.ProtoReflect.Descriptor instead.
func (*ApproveStageEventResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{28}
}

func (x *ApproveStageEventResponse) GetEvent() *StageEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type Connection_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Connection_FilterType  `protobuf:"varint,1,opt,name=type,proto3,enum=InternalApi.Delivery.Connection_FilterType" json:"type,omitempty"`
	Data          *Connection_DataFilter `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection_Filter) Reset() {
	*x = Connection_Filter{}
	mi := &file_delivery_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection_Filter) ProtoMessage() {}

func (x *Connection_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection_Filter.ProtoReflect.Descriptor instead.
func (*Connection_Filter) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{12, 0}
}

func (x *Connection_Filter) GetType() Connection_FilterType {
	if x != nil {
		return x.Type
	}
	return Connection_FILTER_TYPE_UNKNOWN
}

func (x *Connection_Filter) GetData() *Connection_DataFilter {
	if x != nil {
		return x.Data
	}
	return nil
}

type Connection_DataFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection_DataFilter) Reset() {
	*x = Connection_DataFilter{}
	mi := &file_delivery_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection_DataFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection_DataFilter) ProtoMessage() {}

func (x *Connection_DataFilter) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection_DataFilter.ProtoReflect.Descriptor instead.
func (*Connection_DataFilter) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{12, 1}
}

func (x *Connection_DataFilter) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type StageCreated struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	CanvasId      string                      `protobuf:"bytes,1,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	StageId       string                      `protobuf:"bytes,2,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	Timestamp     *timestamp.Timestamp        `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageCreated) Reset() {
	*x = StageCreated{}
	mi := &file_delivery_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageCreated) ProtoMessage() {}

func (x *StageCreated) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*StageCreated) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{31}
}

func (x *StageCreated) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *StageCreated) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageCreated) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type EventSourceCreated struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	CanvasId      string                      `protobuf:"bytes,1,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	SourceId      string                      `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Timestamp     *timestamp.Timestamp        `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSourceCreated) Reset() {
	*x = EventSourceCreated{}
	mi := &file_delivery_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSourceCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSourceCreated) ProtoMessage() {}

func (x *EventSourceCreated) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*EventSourceCreated) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{32}
}

func (x *EventSourceCreated) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *EventSourceCreated) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *EventSourceCreated) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StageEventCreated struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	CanvasId      string                      `protobuf:"bytes,1,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	StageId       string                      `protobuf:"bytes,2,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	EventId       string                      `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp     *timestamp.Timestamp        `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageEventCreated) Reset() {
	*x = StageEventCreated{}
	mi := &file_delivery_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageEventCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageEventCreated) ProtoMessage() {}

func (x *StageEventCreated) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*StageEventCreated) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{33}
}

func (x *StageEventCreated) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *StageEventCreated) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageEventCreated) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *StageEventCreated) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StageEventApproved struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	CanvasId      string                      `protobuf:"bytes,1,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	StageId       string                      `protobuf:"bytes,2,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	EventId       string                      `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp     *timestamp.Timestamp        `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageEventApproved) Reset() {
	*x = StageEventApproved{}
	mi := &file_delivery_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageEventApproved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageEventApproved) ProtoMessage() {}

func (x *StageEventApproved) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*StageEventApproved) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{34}
}

func (x *StageEventApproved) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *StageEventApproved) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageEventApproved) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StageExecutionCreated struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	CanvasId      string                      `protobuf:"bytes,1,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	ExecutionId   string                      `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	StageId       string                      `protobuf:"bytes,3,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	EventId       string                      `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp     *timestamp.Timestamp        `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageExecutionCreated) Reset() {
	*x = StageExecutionCreated{}
	mi := &file_delivery_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageExecutionCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageExecutionCreated) ProtoMessage() {}

func (x *StageExecutionCreated) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*StageExecutionCreated) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{35}
}

func (x *StageExecutionCreated) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *StageExecutionCreated) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *StageExecutionCreated) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageExecutionCreated) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *StageExecutionCreated) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StageExecutionStarted struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	CanvasId      string                      `protobuf:"bytes,1,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	ExecutionId   string                      `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	StageId       string                      `protobuf:"bytes,3,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	EventId       string                      `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp     *timestamp.Timestamp        `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageExecutionStarted) Reset() {
	*x = StageExecutionStarted{}
	mi := &file_delivery_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageExecutionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageExecutionStarted) ProtoMessage() {}

func (x *StageExecutionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*StageExecutionStarted) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{36}
}

func (x *StageExecutionStarted) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *StageExecutionStarted) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *StageExecutionStarted) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageExecutionStarted) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *StageExecutionStarted) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StageExecutionFinished struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	CanvasId      string                      `protobuf:"bytes,1,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	ExecutionId   string                      `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	StageId       string                      `protobuf:"bytes,3,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	EventId       string                      `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp     *timestamp.Timestamp        `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageExecutionFinished) Reset() {
	*x = StageExecutionFinished{}
	mi := &file_delivery_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageExecutionFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageExecutionFinished) ProtoMessage() {}

func (x *StageExecutionFinished) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*StageExecutionFinished) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{37}
}

func (x *StageExecutionFinished) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *StageExecutionFinished) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *StageExecutionFinished) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageExecutionFinished) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *StageExecutionFinished) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_delivery_proto protoreflect.FileDescriptor

const file_delivery_proto_rawDesc = "" +
	"\n" +
	"\x0edelivery.proto\x12\x14InternalApi.Delivery\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x01\n" +
	"\x06Canvas\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"u\n" +
	"\x13CreateCanvasRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12!\n" +
	"\frequester_id\x18\x03 \x01(\tR\vrequesterId\"L\n" +
	"\x14CreateCanvasResponse\x124\n" +
	"\x06canvas\x18\x01 \x01(\v2\x1c.InternalApi.Delivery.CanvasR\x06canvas\"d\n" +
	"\x15DescribeCanvasRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\"N\n" +
	"\x16DescribeCanvasResponse\x124\n" +
	"\x06canvas\x18\x01 \x01(\v2\x1c.InternalApi.Delivery.CanvasR\x06canvas\"\xb2\x01\n" +
	"\vEventSource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x04 \x01(\tR\bcanvasId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x80\x01\n" +
	"\x14DescribeStageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x04 \x01(\tR\bcanvasId\"J\n" +
	"\x15DescribeStageResponse\x121\n" +
	"\x05stage\x18\x01 \x01(\v2\x1b.InternalApi.Delivery.StageR\x05stage\"\x97\x01\n" +
	"\x18CreateEventSourceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x03 \x01(\tR\bcanvasId\x12!\n" +
	"\frequester_id\x18\x04 \x01(\tR\vrequesterId\"s\n" +
	"\x19CreateEventSourceResponse\x12D\n" +
	"\fevent_source\x18\x01 \x01(\v2!.InternalApi.Delivery.EventSourceR\veventSource\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x86\x01\n" +
	"\x1aDescribeEventSourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x04 \x01(\tR\bcanvasId\"c\n" +
	"\x1bDescribeEventSourceResponse\x12D\n" +
	"\fevent_source\x18\x01 \x01(\v2!.InternalApi.Delivery.EventSourceR\veventSource\"\xf4\x04\n" +
	"\n" +
	"Connection\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.InternalApi.Delivery.Connection.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12A\n" +
	"\afilters\x18\x03 \x03(\v2'.InternalApi.Delivery.Connection.FilterR\afilters\x12X\n" +
	"\x0ffilter_operator\x18\x04 \x01(\x0e2/.InternalApi.Delivery.Connection.FilterOperatorR\x0efilterOperator\x1a\x8a\x01\n" +
	"\x06Filter\x12?\n" +
	"\x04type\x18\x01 \x01(\x0e2+.InternalApi.Delivery.Connection.FilterTypeR\x04type\x12?\n" +
	"\x04data\x18\x02 \x01(\v2+.InternalApi.Delivery.Connection.DataFilterR\x04data\x1a,\n" +
	"\n" +
	"DataFilter\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\"?\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11TYPE_EVENT_SOURCE\x10\x01\x12\x0e\n" +
	"\n" +
	"TYPE_STAGE\x10\x02\";\n" +
	"\n" +
	"FilterType\x12\x17\n" +
	"\x13FILTER_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10FILTER_TYPE_DATA\x10\x01\"A\n" +
	"\x0eFilterOperator\x12\x17\n" +
	"\x13FILTER_OPERATOR_AND\x10\x00\x12\x16\n" +
	"\x12FILTER_OPERATOR_OR\x10\x01\"\xe3\x02\n" +
	"\x05Stage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x04 \x01(\tR\bcanvasId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\vconnections\x18\x06 \x03(\v2 .InternalApi.Delivery.ConnectionR\vconnections\x12+\n" +
	"\x11approval_required\x18\a \x01(\bR\x10approvalRequired\x12D\n" +
	"\frun_template\x18\b \x01(\v2!.InternalApi.Delivery.RunTemplateR\vrunTemplate\"\xc8\x02\n" +
	"\x12CreateStageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x03 \x01(\tR\bcanvasId\x12B\n" +
	"\vconnections\x18\x04 \x03(\v2 .InternalApi.Delivery.ConnectionR\vconnections\x12+\n" +
	"\x11approval_required\x18\x05 \x01(\bR\x10approvalRequired\x12!\n" +
	"\frequester_id\x18\x06 \x01(\tR\vrequesterId\x12D\n" +
	"\frun_template\x18\a \x01(\v2!.InternalApi.Delivery.RunTemplateR\vrunTemplate\"\xc1\x01\n" +
	"\vRunTemplate\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.InternalApi.Delivery.RunTemplate.TypeR\x04type\x12H\n" +
	"\tsemaphore\x18\x02 \x01(\v2*.InternalApi.Delivery.SemaphoreRunTemplateR\tsemaphore\",\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eTYPE_SEMAPHORE\x10\x01\"\xa6\x02\n" +
	"\x14SemaphoreRunTemplate\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12#\n" +
	"\rpipeline_file\x18\x03 \x01(\tR\fpipelineFile\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12Z\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v2:.InternalApi.Delivery.SemaphoreRunTemplate.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x13CreateStageResponse\x121\n" +
	"\x05stage\x18\x01 \x01(\v2\x1b.InternalApi.Delivery.StageR\x05stage\"\x8b\x01\n" +
	"\x12UpdateStageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12B\n" +
	"\vconnections\x18\x02 \x03(\v2 .InternalApi.Delivery.ConnectionR\vconnections\x12!\n" +
	"\frequester_id\x18\x03 \x01(\tR\vrequesterId\"H\n" +
	"\x13UpdateStageResponse\x121\n" +
	"\x05stage\x18\x01 \x01(\v2\x1b.InternalApi.Delivery.StageR\x05stage\"Y\n" +
	"\x11ListStagesRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x02 \x01(\tR\bcanvasId\"I\n" +
	"\x12ListStagesResponse\x123\n" +
	"\x06stages\x18\x01 \x03(\v2\x1b.InternalApi.Delivery.StageR\x06stages\"_\n" +
	"\x17ListEventSourcesRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x02 \x01(\tR\bcanvasId\"b\n" +
	"\x18ListEventSourcesResponse\x12F\n" +
	"\revent_sources\x18\x01 \x03(\v2!.InternalApi.Delivery.EventSourceR\feventSources\"\xb9\x01\n" +
	"\x16ListStageEventsRequest\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x03 \x01(\tR\bcanvasId\x12>\n" +
	"\x06states\x18\x04 \x03(\x0e2&.InternalApi.Delivery.StageEvent.StateR\x06states\"S\n" +
	"\x17ListStageEventsResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .InternalApi.Delivery.StageEventR\x06events\"\xc1\x03\n" +
	"\n" +
	"StageEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12F\n" +
	"\vsource_type\x18\x03 \x01(\x0e2%.InternalApi.Delivery.Connection.TypeR\n" +
	"sourceType\x12<\n" +
	"\x05state\x18\x04 \x01(\x0e2&.InternalApi.Delivery.StageEvent.StateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vapproved_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"approvedAt\x12\x1f\n" +
	"\vapproved_by\x18\a \x01(\tR\n" +
	"approvedBy\"g\n" +
	"\x05State\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x18\n" +
	"\x14WAITING_FOR_APPROVAL\x10\x02\x12\x1b\n" +
	"\x17WAITING_FOR_TIME_WINDOW\x10\x03\x12\r\n" +
	"\tPROCESSED\x10\x04\"\xb9\x01\n" +
	"\x18ApproveStageEventRequest\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x03 \x01(\tR\bcanvasId\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x12!\n" +
	"\frequester_id\x18\x05 \x01(\tR\vrequesterId\"S\n" +
	"\x19ApproveStageEventResponse\x126\n" +
	"\x05event\x18\x01 \x01(\v2 .InternalApi.Delivery.StageEventR\x05event2\xbc\t\n" +
	"\bDelivery\x12e\n" +
	"\fCreateCanvas\x12).InternalApi.Delivery.CreateCanvasRequest\x1a*.InternalApi.Delivery.CreateCanvasResponse\x12t\n" +
	"\x11CreateEventSource\x12..InternalApi.Delivery.CreateEventSourceRequest\x1a/.InternalApi.Delivery.CreateEventSourceResponse\x12b\n" +
	"\vCreateStage\x12(.InternalApi.Delivery.CreateStageRequest\x1a).InternalApi.Delivery.CreateStageResponse\x12k\n" +
	"\x0eDescribeCanvas\x12+.InternalApi.Delivery.DescribeCanvasRequest\x1a,.InternalApi.Delivery.DescribeCanvasResponse\x12h\n" +
	"\rDescribeStage\x12*.InternalApi.Delivery.DescribeStageRequest\x1a+.InternalApi.Delivery.DescribeStageResponse\x12z\n" +
	"\x13DescribeEventSource\x120.InternalApi.Delivery.DescribeEventSourceRequest\x1a1.InternalApi.Delivery.DescribeEventSourceResponse\x12_\n" +
	"\n" +
	"ListStages\x12'.InternalApi.Delivery.ListStagesRequest\x1a(.InternalApi.Delivery.ListStagesResponse\x12q\n" +
	"\x10ListEventSources\x12-.InternalApi.Delivery.ListEventSourcesRequest\x1a..InternalApi.Delivery.ListEventSourcesResponse\x12n\n" +
	"\x0fListStageEvents\x12,.InternalApi.Delivery.ListStageEventsRequest\x1a-.InternalApi.Delivery.ListStageEventsResponse\x12b\n" +
	"\vUpdateStage\x12(.InternalApi.Delivery.UpdateStageRequest\x1a).InternalApi.Delivery.UpdateStageResponse\x12t\n" +
	"\x11ApproveStageEvent\x12..InternalApi.Delivery.ApproveStageEventRequest\x1a/.InternalApi.Delivery.ApproveStageEventResponseBCZAgithub.com/semaphoreio/semaphore/delivery-hub/pkg/protos/deliveryb\x06proto3"

var (
	file_delivery_proto_rawDescOnce sync.Once
	file_delivery_proto_rawDescData []byte
)

func file_delivery_proto_rawDescGZIP() []byte {
	file_delivery_proto_rawDescOnce.Do(func() {
		file_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_proto_rawDesc), len(file_delivery_proto_rawDesc)))
	})
	return file_delivery_proto_rawDescData
}

var file_delivery_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_delivery_proto_goTypes = []any{
	(Connection_Type)(0),                // 0: InternalApi.Delivery.Connection.Type
	(Connection_FilterType)(0),          // 1: InternalApi.Delivery.Connection.FilterType
	(Connection_FilterOperator)(0),      // 2: InternalApi.Delivery.Connection.FilterOperator
	(RunTemplate_Type)(0),               // 3: InternalApi.Delivery.RunTemplate.Type
	(StageEvent_State)(0),               // 4: InternalApi.Delivery.StageEvent.State
	(*Canvas)(nil),                      // 5: InternalApi.Delivery.Canvas
	(*CreateCanvasRequest)(nil),         // 6: InternalApi.Delivery.CreateCanvasRequest
	(*CreateCanvasResponse)(nil),        // 7: InternalApi.Delivery.CreateCanvasResponse
	(*DescribeCanvasRequest)(nil),       // 8: InternalApi.Delivery.DescribeCanvasRequest
	(*DescribeCanvasResponse)(nil),      // 9: InternalApi.Delivery.DescribeCanvasResponse
	(*EventSource)(nil),                 // 10: InternalApi.Delivery.EventSource
	(*DescribeStageRequest)(nil),        // 11: InternalApi.Delivery.DescribeStageRequest
	(*DescribeStageResponse)(nil),       // 12: InternalApi.Delivery.DescribeStageResponse
	(*CreateEventSourceRequest)(nil),    // 13: InternalApi.Delivery.CreateEventSourceRequest
	(*CreateEventSourceResponse)(nil),   // 14: InternalApi.Delivery.CreateEventSourceResponse
	(*DescribeEventSourceRequest)(nil),  // 15: InternalApi.Delivery.DescribeEventSourceRequest
	(*DescribeEventSourceResponse)(nil), // 16: InternalApi.Delivery.DescribeEventSourceResponse
	(*Connection)(nil),                  // 17: InternalApi.Delivery.Connection
	(*Stage)(nil),                       // 18: InternalApi.Delivery.Stage
	(*CreateStageRequest)(nil),          // 19: InternalApi.Delivery.CreateStageRequest
	(*RunTemplate)(nil),                 // 20: InternalApi.Delivery.RunTemplate
	(*SemaphoreRunTemplate)(nil),        // 21: InternalApi.Delivery.SemaphoreRunTemplate
	(*CreateStageResponse)(nil),         // 22: InternalApi.Delivery.CreateStageResponse
	(*UpdateStageRequest)(nil),          // 23: InternalApi.Delivery.UpdateStageRequest
	(*UpdateStageResponse)(nil),         // 24: InternalApi.Delivery.UpdateStageResponse
	(*ListStagesRequest)(nil),           // 25: InternalApi.Delivery.ListStagesRequest
	(*ListStagesResponse)(nil),          // 26: InternalApi.Delivery.ListStagesResponse
	(*ListEventSourcesRequest)(nil),     // 27: InternalApi.Delivery.ListEventSourcesRequest
	(*ListEventSourcesResponse)(nil),    // 28: InternalApi.Delivery.ListEventSourcesResponse
	(*ListStageEventsRequest)(nil),      // 29: InternalApi.Delivery.ListStageEventsRequest
	(*ListStageEventsResponse)(nil),     // 30: InternalApi.Delivery.ListStageEventsResponse
	(*StageEvent)(nil),                  // 31: InternalApi.Delivery.StageEvent
	(*ApproveStageEventRequest)(nil),    // 32: InternalApi.Delivery.ApproveStageEventRequest
	(*ApproveStageEventResponse)(nil),   // 33: InternalApi.Delivery.ApproveStageEventResponse
	(*Connection_Filter)(nil),           // 34: InternalApi.Delivery.Connection.Filter
	(*Connection_DataFilter)(nil),       // 35: InternalApi.Delivery.Connection.DataFilter
	nil,                                 // 36: InternalApi.Delivery.SemaphoreRunTemplate.ParametersEntry
	(*timestamp.Timestamp)(nil),         // 37: google.protobuf.Timestamp
}
var file_delivery_proto_depIdxs = []int32{
	37, // 0: InternalApi.Delivery.Canvas.created_at:type_name -> google.protobuf.Timestamp
	5,  // 1: InternalApi.Delivery.CreateCanvasResponse.canvas:type_name -> InternalApi.Delivery.Canvas
	5,  // 2: InternalApi.Delivery.DescribeCanvasResponse.canvas:type_name -> InternalApi.Delivery.Canvas
	37, // 3: InternalApi.Delivery.EventSource.created_at:type_name -> google.protobuf.Timestamp
	18, // 4: InternalApi.Delivery.DescribeStageResponse.stage:type_name -> InternalApi.Delivery.Stage
	10, // 5: InternalApi.Delivery.CreateEventSourceResponse.event_source:type_name -> InternalApi.Delivery.EventSource
	10, // 6: InternalApi.Delivery.DescribeEventSourceResponse.event_source:type_name -> InternalApi.Delivery.EventSource
	0,  // 7: InternalApi.Delivery.Connection.type:type_name -> InternalApi.Delivery.Connection.Type
	34, // 8: InternalApi.Delivery.Connection.filters:type_name -> InternalApi.Delivery.Connection.Filter
	2,  // 9: InternalApi.Delivery.Connection.filter_operator:type_name -> InternalApi.Delivery.Connection.FilterOperator
	37, // 10: InternalApi.Delivery.Stage.created_at:type_name -> google.protobuf.Timestamp
	17, // 11: InternalApi.Delivery.Stage.connections:type_name -> InternalApi.Delivery.Connection
	20, // 12: InternalApi.Delivery.Stage.run_template:type_name -> InternalApi.Delivery.RunTemplate
	17, // 13: InternalApi.Delivery.CreateStageRequest.connections:type_name -> InternalApi.Delivery.Connection
	20, // 14: InternalApi.Delivery.CreateStageRequest.run_template:type_name -> InternalApi.Delivery.RunTemplate
	3,  // 15: InternalApi.Delivery.RunTemplate.type:type_name -> InternalApi.Delivery.RunTemplate.Type
	21, // 16: InternalApi.Delivery.RunTemplate.semaphore:type_name -> InternalApi.Delivery.SemaphoreRunTemplate
	36, // 17: InternalApi.Delivery.SemaphoreRunTemplate.parameters:type_name -> InternalApi.Delivery.SemaphoreRunTemplate.ParametersEntry
	18, // 18: InternalApi.Delivery.CreateStageResponse.stage:type_name -> InternalApi.Delivery.Stage
	17, // 19: InternalApi.Delivery.UpdateStageRequest.connections:type_name -> InternalApi.Delivery.Connection
	18, // 20: InternalApi.Delivery.UpdateStageResponse.stage:type_name -> InternalApi.Delivery.Stage
	18, // 21: InternalApi.Delivery.ListStagesResponse.stages:type_name -> InternalApi.Delivery.Stage
	10, // 22: InternalApi.Delivery.ListEventSourcesResponse.event_sources:type_name -> InternalApi.Delivery.EventSource
	4,  // 23: InternalApi.Delivery.ListStageEventsRequest.states:type_name -> InternalApi.Delivery.StageEvent.State
	31, // 24: InternalApi.Delivery.ListStageEventsResponse.events:type_name -> InternalApi.Delivery.StageEvent
	0,  // 25: InternalApi.Delivery.StageEvent.source_type:type_name -> InternalApi.Delivery.Connection.Type
	4,  // 26: InternalApi.Delivery.StageEvent.state:type_name -> InternalApi.Delivery.StageEvent.State
	37, // 27: InternalApi.Delivery.StageEvent.created_at:type_name -> google.protobuf.Timestamp
	37, // 28: InternalApi.Delivery.StageEvent.approved_at:type_name -> google.protobuf.Timestamp
	31, // 29: InternalApi.Delivery.ApproveStageEventResponse.event:type_name -> InternalApi.Delivery.StageEvent
	1,  // 30: InternalApi.Delivery.Connection.Filter.type:type_name -> InternalApi.Delivery.Connection.FilterType
	35, // 31: InternalApi.Delivery.Connection.Filter.data:type_name -> InternalApi.Delivery.Connection.DataFilter
	6,  // 32: InternalApi.Delivery.Delivery.CreateCanvas:input_type -> InternalApi.Delivery.CreateCanvasRequest
	13, // 33: InternalApi.Delivery.Delivery.CreateEventSource:input_type -> InternalApi.Delivery.CreateEventSourceRequest
	19, // 34: InternalApi.Delivery.Delivery.CreateStage:input_type -> InternalApi.Delivery.CreateStageRequest
	8,  // 35: InternalApi.Delivery.Delivery.DescribeCanvas:input_type -> InternalApi.Delivery.DescribeCanvasRequest
	11, // 36: InternalApi.Delivery.Delivery.DescribeStage:input_type -> InternalApi.Delivery.DescribeStageRequest
	15, // 37: InternalApi.Delivery.Delivery.DescribeEventSource:input_type -> InternalApi.Delivery.DescribeEventSourceRequest
	25, // 38: InternalApi.Delivery.Delivery.ListStages:input_type -> InternalApi.Delivery.ListStagesRequest
	27, // 39: InternalApi.Delivery.Delivery.ListEventSources:input_type -> InternalApi.Delivery.ListEventSourcesRequest
	29, // 40: InternalApi.Delivery.Delivery.ListStageEvents:input_type -> InternalApi.Delivery.ListStageEventsRequest
	23, // 41: InternalApi.Delivery.Delivery.UpdateStage:input_type -> InternalApi.Delivery.UpdateStageRequest
	32, // 42: InternalApi.Delivery.Delivery.ApproveStageEvent:input_type -> InternalApi.Delivery.ApproveStageEventRequest
	7,  // 43: InternalApi.Delivery.Delivery.CreateCanvas:output_type -> InternalApi.Delivery.CreateCanvasResponse
	14, // 44: InternalApi.Delivery.Delivery.CreateEventSource:output_type -> InternalApi.Delivery.CreateEventSourceResponse
	22, // 45: InternalApi.Delivery.Delivery.CreateStage:output_type -> InternalApi.Delivery.CreateStageResponse
	9,  // 46: InternalApi.Delivery.Delivery.DescribeCanvas:output_type -> InternalApi.Delivery.DescribeCanvasResponse
	12, // 47: InternalApi.Delivery.Delivery.DescribeStage:output_type -> InternalApi.Delivery.DescribeStageResponse
	16, // 48: InternalApi.Delivery.Delivery.DescribeEventSource:output_type -> InternalApi.Delivery.DescribeEventSourceResponse
	26, // 49: InternalApi.Delivery.Delivery.ListStages:output_type -> InternalApi.Delivery.ListStagesResponse
	28, // 50: InternalApi.Delivery.Delivery.ListEventSources:output_type -> InternalApi.Delivery.ListEventSourcesResponse
	30, // 51: InternalApi.Delivery.Delivery.ListStageEvents:output_type -> InternalApi.Delivery.ListStageEventsResponse
	24, // 52: InternalApi.Delivery.Delivery.UpdateStage:output_type -> InternalApi.Delivery.UpdateStageResponse
	33, // 53: InternalApi.Delivery.Delivery.ApproveStageEvent:output_type -> InternalApi.Delivery.ApproveStageEventResponse
	43, // [43:54] is the sub-list for method output_type
	32, // [32:43] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_delivery_proto_init() }
func file_delivery_proto_init() {
	if File_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_proto_rawDesc), len(file_delivery_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_proto_goTypes,
		DependencyIndexes: file_delivery_proto_depIdxs,
		EnumInfos:         file_delivery_proto_enumTypes,
		MessageInfos:      file_delivery_proto_msgTypes,
	}.Build()
	File_delivery_proto = out.File
	file_delivery_proto_goTypes = nil
	file_delivery_proto_depIdxs = nil
}
