// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.3.0
// source: delivery.proto

package delivery

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Connection_Type int32

const (
	Connection_TYPE_UNKNOWN      Connection_Type = 0
	Connection_TYPE_EVENT_SOURCE Connection_Type = 1
	Connection_TYPE_STAGE        Connection_Type = 2
)

// Enum value maps for Connection_Type.
var (
	Connection_Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_EVENT_SOURCE",
		2: "TYPE_STAGE",
	}
	Connection_Type_value = map[string]int32{
		"TYPE_UNKNOWN":      0,
		"TYPE_EVENT_SOURCE": 1,
		"TYPE_STAGE":        2,
	}
)

func (x Connection_Type) Enum() *Connection_Type {
	p := new(Connection_Type)
	*p = x
	return p
}

func (x Connection_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Connection_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_proto_enumTypes[0].Descriptor()
}

func (Connection_Type) Type() protoreflect.EnumType {
	return &file_delivery_proto_enumTypes[0]
}

func (x Connection_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Connection_Type.Descriptor instead.
func (Connection_Type) EnumDescriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{10, 0}
}

type RunTemplate_Type int32

const (
	RunTemplate_TYPE_UNKNOWN            RunTemplate_Type = 0
	RunTemplate_TYPE_SEMAPHORE_WORKFLOW RunTemplate_Type = 1
	RunTemplate_TYPE_SEMAPHORE_TASK     RunTemplate_Type = 2
)

// Enum value maps for RunTemplate_Type.
var (
	RunTemplate_Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_SEMAPHORE_WORKFLOW",
		2: "TYPE_SEMAPHORE_TASK",
	}
	RunTemplate_Type_value = map[string]int32{
		"TYPE_UNKNOWN":            0,
		"TYPE_SEMAPHORE_WORKFLOW": 1,
		"TYPE_SEMAPHORE_TASK":     2,
	}
)

func (x RunTemplate_Type) Enum() *RunTemplate_Type {
	p := new(RunTemplate_Type)
	*p = x
	return p
}

func (x RunTemplate_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunTemplate_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_proto_enumTypes[1].Descriptor()
}

func (RunTemplate_Type) Type() protoreflect.EnumType {
	return &file_delivery_proto_enumTypes[1]
}

func (x RunTemplate_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunTemplate_Type.Descriptor instead.
func (RunTemplate_Type) EnumDescriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{13, 0}
}

type Canvas struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Stages         []*Stage               `protobuf:"bytes,5,rep,name=stages,proto3" json:"stages,omitempty"`
	EventSources   []*EventSource         `protobuf:"bytes,6,rep,name=event_sources,json=eventSources,proto3" json:"event_sources,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Canvas) Reset() {
	*x = Canvas{}
	mi := &file_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Canvas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Canvas) ProtoMessage() {}

func (x *Canvas) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Canvas.ProtoReflect.Descriptor instead.
func (*Canvas) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *Canvas) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Canvas) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Canvas) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Canvas) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Canvas) GetStages() []*Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *Canvas) GetEventSources() []*EventSource {
	if x != nil {
		return x.EventSources
	}
	return nil
}

type CreateCanvasRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	RequesterId    string                 `protobuf:"bytes,3,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCanvasRequest) Reset() {
	*x = CreateCanvasRequest{}
	mi := &file_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCanvasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCanvasRequest) ProtoMessage() {}

func (x *CreateCanvasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCanvasRequest.ProtoReflect.Descriptor instead.
func (*CreateCanvasRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCanvasRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCanvasRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateCanvasRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type CreateCanvasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Canvas        *Canvas                `protobuf:"bytes,1,opt,name=canvas,proto3" json:"canvas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCanvasResponse) Reset() {
	*x = CreateCanvasResponse{}
	mi := &file_delivery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCanvasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCanvasResponse) ProtoMessage() {}

func (x *CreateCanvasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCanvasResponse.ProtoReflect.Descriptor instead.
func (*CreateCanvasResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCanvasResponse) GetCanvas() *Canvas {
	if x != nil {
		return x.Canvas
	}
	return nil
}

type DescribeCanvasRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DescribeCanvasRequest) Reset() {
	*x = DescribeCanvasRequest{}
	mi := &file_delivery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCanvasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCanvasRequest) ProtoMessage() {}

func (x *DescribeCanvasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCanvasRequest.ProtoReflect.Descriptor instead.
func (*DescribeCanvasRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeCanvasRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DescribeCanvasRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type DescribeCanvasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Canvas        *Canvas                `protobuf:"bytes,1,opt,name=canvas,proto3" json:"canvas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeCanvasResponse) Reset() {
	*x = DescribeCanvasResponse{}
	mi := &file_delivery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCanvasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCanvasResponse) ProtoMessage() {}

func (x *DescribeCanvasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCanvasResponse.ProtoReflect.Descriptor instead.
func (*DescribeCanvasResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeCanvasResponse) GetCanvas() *Canvas {
	if x != nil {
		return x.Canvas
	}
	return nil
}

type EventSource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId       string                 `protobuf:"bytes,4,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventSource) Reset() {
	*x = EventSource{}
	mi := &file_delivery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSource) ProtoMessage() {}

func (x *EventSource) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSource.ProtoReflect.Descriptor instead.
func (*EventSource) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{5}
}

func (x *EventSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventSource) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *EventSource) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *EventSource) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateEventSourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId       string                 `protobuf:"bytes,3,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	RequesterId    string                 `protobuf:"bytes,4,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateEventSourceRequest) Reset() {
	*x = CreateEventSourceRequest{}
	mi := &file_delivery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventSourceRequest) ProtoMessage() {}

func (x *CreateEventSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventSourceRequest.ProtoReflect.Descriptor instead.
func (*CreateEventSourceRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{6}
}

func (x *CreateEventSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEventSourceRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateEventSourceRequest) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *CreateEventSourceRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type CreateEventSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventSource   *EventSource           `protobuf:"bytes,1,opt,name=event_source,json=eventSource,proto3" json:"event_source,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventSourceResponse) Reset() {
	*x = CreateEventSourceResponse{}
	mi := &file_delivery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventSourceResponse) ProtoMessage() {}

func (x *CreateEventSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventSourceResponse.ProtoReflect.Descriptor instead.
func (*CreateEventSourceResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{7}
}

func (x *CreateEventSourceResponse) GetEventSource() *EventSource {
	if x != nil {
		return x.EventSource
	}
	return nil
}

func (x *CreateEventSourceResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DescribeEventSourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId       string                 `protobuf:"bytes,3,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DescribeEventSourceRequest) Reset() {
	*x = DescribeEventSourceRequest{}
	mi := &file_delivery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeEventSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeEventSourceRequest) ProtoMessage() {}

func (x *DescribeEventSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeEventSourceRequest.ProtoReflect.Descriptor instead.
func (*DescribeEventSourceRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{8}
}

func (x *DescribeEventSourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DescribeEventSourceRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DescribeEventSourceRequest) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

type DescribeEventSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventSource   *EventSource           `protobuf:"bytes,1,opt,name=event_source,json=eventSource,proto3" json:"event_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeEventSourceResponse) Reset() {
	*x = DescribeEventSourceResponse{}
	mi := &file_delivery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeEventSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeEventSourceResponse) ProtoMessage() {}

func (x *DescribeEventSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeEventSourceResponse.ProtoReflect.Descriptor instead.
func (*DescribeEventSourceResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{9}
}

func (x *DescribeEventSourceResponse) GetEventSource() *EventSource {
	if x != nil {
		return x.EventSource
	}
	return nil
}

type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Connection_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=InternalApi.Delivery.Connection_Type" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_delivery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{10}
}

func (x *Connection) GetType() Connection_Type {
	if x != nil {
		return x.Type
	}
	return Connection_TYPE_UNKNOWN
}

func (x *Connection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Stage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId         string                 `protobuf:"bytes,4,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	CreatedAt        *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Connections      []*Connection          `protobuf:"bytes,6,rep,name=connections,proto3" json:"connections,omitempty"`
	ApprovalRequired bool                   `protobuf:"varint,7,opt,name=approval_required,json=approvalRequired,proto3" json:"approval_required,omitempty"`
	RunTemplate      *RunTemplate           `protobuf:"bytes,8,opt,name=run_template,json=runTemplate,proto3" json:"run_template,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_delivery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{11}
}

func (x *Stage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Stage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stage) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Stage) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *Stage) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Stage) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *Stage) GetApprovalRequired() bool {
	if x != nil {
		return x.ApprovalRequired
	}
	return false
}

func (x *Stage) GetRunTemplate() *RunTemplate {
	if x != nil {
		return x.RunTemplate
	}
	return nil
}

type CreateStageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CanvasId         string                 `protobuf:"bytes,3,opt,name=canvas_id,json=canvasId,proto3" json:"canvas_id,omitempty"`
	Connections      []*Connection          `protobuf:"bytes,4,rep,name=connections,proto3" json:"connections,omitempty"`
	ApprovalRequired bool                   `protobuf:"varint,5,opt,name=approval_required,json=approvalRequired,proto3" json:"approval_required,omitempty"`
	RequesterId      string                 `protobuf:"bytes,6,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	RunTemplate      *RunTemplate           `protobuf:"bytes,7,opt,name=run_template,json=runTemplate,proto3" json:"run_template,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateStageRequest) Reset() {
	*x = CreateStageRequest{}
	mi := &file_delivery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStageRequest) ProtoMessage() {}

func (x *CreateStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStageRequest.ProtoReflect.Descriptor instead.
func (*CreateStageRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{12}
}

func (x *CreateStageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStageRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateStageRequest) GetCanvasId() string {
	if x != nil {
		return x.CanvasId
	}
	return ""
}

func (x *CreateStageRequest) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *CreateStageRequest) GetApprovalRequired() bool {
	if x != nil {
		return x.ApprovalRequired
	}
	return false
}

func (x *CreateStageRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *CreateStageRequest) GetRunTemplate() *RunTemplate {
	if x != nil {
		return x.RunTemplate
	}
	return nil
}

type RunTemplate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              RunTemplate_Type       `protobuf:"varint,1,opt,name=type,proto3,enum=InternalApi.Delivery.RunTemplate_Type" json:"type,omitempty"`
	SemaphoreWorkflow *WorkflowTemplate      `protobuf:"bytes,2,opt,name=semaphore_workflow,json=semaphoreWorkflow,proto3" json:"semaphore_workflow,omitempty"`
	SemaphoreTask     *TaskTemplate          `protobuf:"bytes,3,opt,name=semaphore_task,json=semaphoreTask,proto3" json:"semaphore_task,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RunTemplate) Reset() {
	*x = RunTemplate{}
	mi := &file_delivery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTemplate) ProtoMessage() {}

func (x *RunTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTemplate.ProtoReflect.Descriptor instead.
func (*RunTemplate) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{13}
}

func (x *RunTemplate) GetType() RunTemplate_Type {
	if x != nil {
		return x.Type
	}
	return RunTemplate_TYPE_UNKNOWN
}

func (x *RunTemplate) GetSemaphoreWorkflow() *WorkflowTemplate {
	if x != nil {
		return x.SemaphoreWorkflow
	}
	return nil
}

func (x *RunTemplate) GetSemaphoreTask() *TaskTemplate {
	if x != nil {
		return x.SemaphoreTask
	}
	return nil
}

type WorkflowTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	PipelineFile  string                 `protobuf:"bytes,3,opt,name=pipeline_file,json=pipelineFile,proto3" json:"pipeline_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTemplate) Reset() {
	*x = WorkflowTemplate{}
	mi := &file_delivery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTemplate) ProtoMessage() {}

func (x *WorkflowTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTemplate.ProtoReflect.Descriptor instead.
func (*WorkflowTemplate) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{14}
}

func (x *WorkflowTemplate) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *WorkflowTemplate) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *WorkflowTemplate) GetPipelineFile() string {
	if x != nil {
		return x.PipelineFile
	}
	return ""
}

type TaskTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskTemplate) Reset() {
	*x = TaskTemplate{}
	mi := &file_delivery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskTemplate) ProtoMessage() {}

func (x *TaskTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskTemplate.ProtoReflect.Descriptor instead.
func (*TaskTemplate) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{15}
}

func (x *TaskTemplate) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *TaskTemplate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskTemplate) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type CreateStageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         *Stage                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStageResponse) Reset() {
	*x = CreateStageResponse{}
	mi := &file_delivery_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStageResponse) ProtoMessage() {}

func (x *CreateStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStageResponse.ProtoReflect.Descriptor instead.
func (*CreateStageResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{16}
}

func (x *CreateStageResponse) GetStage() *Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

type UpdateStageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Connections   []*Connection          `protobuf:"bytes,2,rep,name=connections,proto3" json:"connections,omitempty"`
	RequesterId   string                 `protobuf:"bytes,3,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStageRequest) Reset() {
	*x = UpdateStageRequest{}
	mi := &file_delivery_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStageRequest) ProtoMessage() {}

func (x *UpdateStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStageRequest.ProtoReflect.Descriptor instead.
func (*UpdateStageRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateStageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStageRequest) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *UpdateStageRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type UpdateStageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         *Stage                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStageResponse) Reset() {
	*x = UpdateStageResponse{}
	mi := &file_delivery_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStageResponse) ProtoMessage() {}

func (x *UpdateStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStageResponse.ProtoReflect.Descriptor instead.
func (*UpdateStageResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateStageResponse) GetStage() *Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

type ListStageEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStageEventsRequest) Reset() {
	*x = ListStageEventsRequest{}
	mi := &file_delivery_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStageEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStageEventsRequest) ProtoMessage() {}

func (x *ListStageEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStageEventsRequest.ProtoReflect.Descriptor instead.
func (*ListStageEventsRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{19}
}

func (x *ListStageEventsRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

type ListStageEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*StageEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStageEventsResponse) Reset() {
	*x = ListStageEventsResponse{}
	mi := &file_delivery_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStageEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStageEventsResponse) ProtoMessage() {}

func (x *ListStageEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStageEventsResponse.ProtoReflect.Descriptor instead.
func (*ListStageEventsResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{20}
}

func (x *ListStageEventsResponse) GetEvents() []*StageEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type StageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceType    Connection_Type        `protobuf:"varint,3,opt,name=source_type,json=sourceType,proto3,enum=InternalApi.Delivery.Connection_Type" json:"source_type,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ApprovedAt    *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,7,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageEvent) Reset() {
	*x = StageEvent{}
	mi := &file_delivery_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageEvent) ProtoMessage() {}

func (x *StageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageEvent.ProtoReflect.Descriptor instead.
func (*StageEvent) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{21}
}

func (x *StageEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StageEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *StageEvent) GetSourceType() Connection_Type {
	if x != nil {
		return x.SourceType
	}
	return Connection_TYPE_UNKNOWN
}

func (x *StageEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StageEvent) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StageEvent) GetApprovedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

func (x *StageEvent) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

type ApproveStageEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,3,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveStageEventRequest) Reset() {
	*x = ApproveStageEventRequest{}
	mi := &file_delivery_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveStageEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveStageEventRequest) ProtoMessage() {}

func (x *ApproveStageEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveStageEventRequest.ProtoReflect.Descriptor instead.
func (*ApproveStageEventRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{22}
}

func (x *ApproveStageEventRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *ApproveStageEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ApproveStageEventRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type ApproveStageEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveStageEventResponse) Reset() {
	*x = ApproveStageEventResponse{}
	mi := &file_delivery_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveStageEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveStageEventResponse) ProtoMessage() {}

func (x *ApproveStageEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveStageEventResponse.ProtoReflect.Descriptor instead.
func (*ApproveStageEventResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_rawDescGZIP(), []int{23}
}

var File_delivery_proto protoreflect.FileDescriptor

const file_delivery_proto_rawDesc = "" +
	"\n" +
	"\x0edelivery.proto\x12\x14InternalApi.Delivery\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x02\n" +
	"\x06Canvas\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\x06stages\x18\x05 \x03(\v2\x1b.InternalApi.Delivery.StageR\x06stages\x12F\n" +
	"\revent_sources\x18\x06 \x03(\v2!.InternalApi.Delivery.EventSourceR\feventSources\"u\n" +
	"\x13CreateCanvasRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12!\n" +
	"\frequester_id\x18\x03 \x01(\tR\vrequesterId\"L\n" +
	"\x14CreateCanvasResponse\x124\n" +
	"\x06canvas\x18\x01 \x01(\v2\x1c.InternalApi.Delivery.CanvasR\x06canvas\"P\n" +
	"\x15DescribeCanvasRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"N\n" +
	"\x16DescribeCanvasResponse\x124\n" +
	"\x06canvas\x18\x01 \x01(\v2\x1c.InternalApi.Delivery.CanvasR\x06canvas\"\xb2\x01\n" +
	"\vEventSource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x04 \x01(\tR\bcanvasId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x97\x01\n" +
	"\x18CreateEventSourceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x03 \x01(\tR\bcanvasId\x12!\n" +
	"\frequester_id\x18\x04 \x01(\tR\vrequesterId\"s\n" +
	"\x19CreateEventSourceResponse\x12D\n" +
	"\fevent_source\x18\x01 \x01(\v2!.InternalApi.Delivery.EventSourceR\veventSource\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"r\n" +
	"\x1aDescribeEventSourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x03 \x01(\tR\bcanvasId\"c\n" +
	"\x1bDescribeEventSourceResponse\x12D\n" +
	"\fevent_source\x18\x01 \x01(\v2!.InternalApi.Delivery.EventSourceR\veventSource\"\x9c\x01\n" +
	"\n" +
	"Connection\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.InternalApi.Delivery.Connection.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"?\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11TYPE_EVENT_SOURCE\x10\x01\x12\x0e\n" +
	"\n" +
	"TYPE_STAGE\x10\x02\"\xe3\x02\n" +
	"\x05Stage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x04 \x01(\tR\bcanvasId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\vconnections\x18\x06 \x03(\v2 .InternalApi.Delivery.ConnectionR\vconnections\x12+\n" +
	"\x11approval_required\x18\a \x01(\bR\x10approvalRequired\x12D\n" +
	"\frun_template\x18\b \x01(\v2!.InternalApi.Delivery.RunTemplateR\vrunTemplate\"\xc8\x02\n" +
	"\x12CreateStageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tcanvas_id\x18\x03 \x01(\tR\bcanvasId\x12B\n" +
	"\vconnections\x18\x04 \x03(\v2 .InternalApi.Delivery.ConnectionR\vconnections\x12+\n" +
	"\x11approval_required\x18\x05 \x01(\bR\x10approvalRequired\x12!\n" +
	"\frequester_id\x18\x06 \x01(\tR\vrequesterId\x12D\n" +
	"\frun_template\x18\a \x01(\v2!.InternalApi.Delivery.RunTemplateR\vrunTemplate\"\xbb\x02\n" +
	"\vRunTemplate\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.InternalApi.Delivery.RunTemplate.TypeR\x04type\x12U\n" +
	"\x12semaphore_workflow\x18\x02 \x01(\v2&.InternalApi.Delivery.WorkflowTemplateR\x11semaphoreWorkflow\x12I\n" +
	"\x0esemaphore_task\x18\x03 \x01(\v2\".InternalApi.Delivery.TaskTemplateR\rsemaphoreTask\"N\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17TYPE_SEMAPHORE_WORKFLOW\x10\x01\x12\x17\n" +
	"\x13TYPE_SEMAPHORE_TASK\x10\x02\"n\n" +
	"\x10WorkflowTemplate\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12#\n" +
	"\rpipeline_file\x18\x03 \x01(\tR\fpipelineFile\"\xd9\x01\n" +
	"\fTaskTemplate\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12R\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v22.InternalApi.Delivery.TaskTemplate.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x13CreateStageResponse\x121\n" +
	"\x05stage\x18\x01 \x01(\v2\x1b.InternalApi.Delivery.StageR\x05stage\"\x8b\x01\n" +
	"\x12UpdateStageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12B\n" +
	"\vconnections\x18\x02 \x03(\v2 .InternalApi.Delivery.ConnectionR\vconnections\x12!\n" +
	"\frequester_id\x18\x03 \x01(\tR\vrequesterId\"H\n" +
	"\x13UpdateStageResponse\x121\n" +
	"\x05stage\x18\x01 \x01(\v2\x1b.InternalApi.Delivery.StageR\x05stage\"3\n" +
	"\x16ListStageEventsRequest\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\"S\n" +
	"\x17ListStageEventsResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .InternalApi.Delivery.StageEventR\x06events\"\xb0\x02\n" +
	"\n" +
	"StageEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12F\n" +
	"\vsource_type\x18\x03 \x01(\x0e2%.InternalApi.Delivery.Connection.TypeR\n" +
	"sourceType\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vapproved_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"approvedAt\x12\x1f\n" +
	"\vapproved_by\x18\a \x01(\tR\n" +
	"approvedBy\"s\n" +
	"\x18ApproveStageEventRequest\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12!\n" +
	"\frequester_id\x18\x03 \x01(\tR\vrequesterId\"\x1b\n" +
	"\x19ApproveStageEventResponse2\x82\x06\n" +
	"\bDelivery\x12e\n" +
	"\fCreateCanvas\x12).InternalApi.Delivery.CreateCanvasRequest\x1a*.InternalApi.Delivery.CreateCanvasResponse\x12k\n" +
	"\x0eDescribeCanvas\x12+.InternalApi.Delivery.DescribeCanvasRequest\x1a,.InternalApi.Delivery.DescribeCanvasResponse\x12t\n" +
	"\x11CreateEventSource\x12..InternalApi.Delivery.CreateEventSourceRequest\x1a/.InternalApi.Delivery.CreateEventSourceResponse\x12b\n" +
	"\vCreateStage\x12(.InternalApi.Delivery.CreateStageRequest\x1a).InternalApi.Delivery.CreateStageResponse\x12b\n" +
	"\vUpdateStage\x12(.InternalApi.Delivery.UpdateStageRequest\x1a).InternalApi.Delivery.UpdateStageResponse\x12n\n" +
	"\x0fListStageEvents\x12,.InternalApi.Delivery.ListStageEventsRequest\x1a-.InternalApi.Delivery.ListStageEventsResponse\x12t\n" +
	"\x11ApproveStageEvent\x12..InternalApi.Delivery.ApproveStageEventRequest\x1a/.InternalApi.Delivery.ApproveStageEventResponseBCZAgithub.com/semaphoreio/semaphore/delivery-hub/pkg/protos/deliveryb\x06proto3"

var (
	file_delivery_proto_rawDescOnce sync.Once
	file_delivery_proto_rawDescData []byte
)

func file_delivery_proto_rawDescGZIP() []byte {
	file_delivery_proto_rawDescOnce.Do(func() {
		file_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_proto_rawDesc), len(file_delivery_proto_rawDesc)))
	})
	return file_delivery_proto_rawDescData
}

var file_delivery_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_delivery_proto_goTypes = []any{
	(Connection_Type)(0),                // 0: InternalApi.Delivery.Connection.Type
	(RunTemplate_Type)(0),               // 1: InternalApi.Delivery.RunTemplate.Type
	(*Canvas)(nil),                      // 2: InternalApi.Delivery.Canvas
	(*CreateCanvasRequest)(nil),         // 3: InternalApi.Delivery.CreateCanvasRequest
	(*CreateCanvasResponse)(nil),        // 4: InternalApi.Delivery.CreateCanvasResponse
	(*DescribeCanvasRequest)(nil),       // 5: InternalApi.Delivery.DescribeCanvasRequest
	(*DescribeCanvasResponse)(nil),      // 6: InternalApi.Delivery.DescribeCanvasResponse
	(*EventSource)(nil),                 // 7: InternalApi.Delivery.EventSource
	(*CreateEventSourceRequest)(nil),    // 8: InternalApi.Delivery.CreateEventSourceRequest
	(*CreateEventSourceResponse)(nil),   // 9: InternalApi.Delivery.CreateEventSourceResponse
	(*DescribeEventSourceRequest)(nil),  // 10: InternalApi.Delivery.DescribeEventSourceRequest
	(*DescribeEventSourceResponse)(nil), // 11: InternalApi.Delivery.DescribeEventSourceResponse
	(*Connection)(nil),                  // 12: InternalApi.Delivery.Connection
	(*Stage)(nil),                       // 13: InternalApi.Delivery.Stage
	(*CreateStageRequest)(nil),          // 14: InternalApi.Delivery.CreateStageRequest
	(*RunTemplate)(nil),                 // 15: InternalApi.Delivery.RunTemplate
	(*WorkflowTemplate)(nil),            // 16: InternalApi.Delivery.WorkflowTemplate
	(*TaskTemplate)(nil),                // 17: InternalApi.Delivery.TaskTemplate
	(*CreateStageResponse)(nil),         // 18: InternalApi.Delivery.CreateStageResponse
	(*UpdateStageRequest)(nil),          // 19: InternalApi.Delivery.UpdateStageRequest
	(*UpdateStageResponse)(nil),         // 20: InternalApi.Delivery.UpdateStageResponse
	(*ListStageEventsRequest)(nil),      // 21: InternalApi.Delivery.ListStageEventsRequest
	(*ListStageEventsResponse)(nil),     // 22: InternalApi.Delivery.ListStageEventsResponse
	(*StageEvent)(nil),                  // 23: InternalApi.Delivery.StageEvent
	(*ApproveStageEventRequest)(nil),    // 24: InternalApi.Delivery.ApproveStageEventRequest
	(*ApproveStageEventResponse)(nil),   // 25: InternalApi.Delivery.ApproveStageEventResponse
	nil,                                 // 26: InternalApi.Delivery.TaskTemplate.ParametersEntry
	(*timestamp.Timestamp)(nil),         // 27: google.protobuf.Timestamp
}
var file_delivery_proto_depIdxs = []int32{
	27, // 0: InternalApi.Delivery.Canvas.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: InternalApi.Delivery.Canvas.stages:type_name -> InternalApi.Delivery.Stage
	7,  // 2: InternalApi.Delivery.Canvas.event_sources:type_name -> InternalApi.Delivery.EventSource
	2,  // 3: InternalApi.Delivery.CreateCanvasResponse.canvas:type_name -> InternalApi.Delivery.Canvas
	2,  // 4: InternalApi.Delivery.DescribeCanvasResponse.canvas:type_name -> InternalApi.Delivery.Canvas
	27, // 5: InternalApi.Delivery.EventSource.created_at:type_name -> google.protobuf.Timestamp
	7,  // 6: InternalApi.Delivery.CreateEventSourceResponse.event_source:type_name -> InternalApi.Delivery.EventSource
	7,  // 7: InternalApi.Delivery.DescribeEventSourceResponse.event_source:type_name -> InternalApi.Delivery.EventSource
	0,  // 8: InternalApi.Delivery.Connection.type:type_name -> InternalApi.Delivery.Connection.Type
	27, // 9: InternalApi.Delivery.Stage.created_at:type_name -> google.protobuf.Timestamp
	12, // 10: InternalApi.Delivery.Stage.connections:type_name -> InternalApi.Delivery.Connection
	15, // 11: InternalApi.Delivery.Stage.run_template:type_name -> InternalApi.Delivery.RunTemplate
	12, // 12: InternalApi.Delivery.CreateStageRequest.connections:type_name -> InternalApi.Delivery.Connection
	15, // 13: InternalApi.Delivery.CreateStageRequest.run_template:type_name -> InternalApi.Delivery.RunTemplate
	1,  // 14: InternalApi.Delivery.RunTemplate.type:type_name -> InternalApi.Delivery.RunTemplate.Type
	16, // 15: InternalApi.Delivery.RunTemplate.semaphore_workflow:type_name -> InternalApi.Delivery.WorkflowTemplate
	17, // 16: InternalApi.Delivery.RunTemplate.semaphore_task:type_name -> InternalApi.Delivery.TaskTemplate
	26, // 17: InternalApi.Delivery.TaskTemplate.parameters:type_name -> InternalApi.Delivery.TaskTemplate.ParametersEntry
	13, // 18: InternalApi.Delivery.CreateStageResponse.stage:type_name -> InternalApi.Delivery.Stage
	12, // 19: InternalApi.Delivery.UpdateStageRequest.connections:type_name -> InternalApi.Delivery.Connection
	13, // 20: InternalApi.Delivery.UpdateStageResponse.stage:type_name -> InternalApi.Delivery.Stage
	23, // 21: InternalApi.Delivery.ListStageEventsResponse.events:type_name -> InternalApi.Delivery.StageEvent
	0,  // 22: InternalApi.Delivery.StageEvent.source_type:type_name -> InternalApi.Delivery.Connection.Type
	27, // 23: InternalApi.Delivery.StageEvent.created_at:type_name -> google.protobuf.Timestamp
	27, // 24: InternalApi.Delivery.StageEvent.approved_at:type_name -> google.protobuf.Timestamp
	3,  // 25: InternalApi.Delivery.Delivery.CreateCanvas:input_type -> InternalApi.Delivery.CreateCanvasRequest
	5,  // 26: InternalApi.Delivery.Delivery.DescribeCanvas:input_type -> InternalApi.Delivery.DescribeCanvasRequest
	8,  // 27: InternalApi.Delivery.Delivery.CreateEventSource:input_type -> InternalApi.Delivery.CreateEventSourceRequest
	14, // 28: InternalApi.Delivery.Delivery.CreateStage:input_type -> InternalApi.Delivery.CreateStageRequest
	19, // 29: InternalApi.Delivery.Delivery.UpdateStage:input_type -> InternalApi.Delivery.UpdateStageRequest
	21, // 30: InternalApi.Delivery.Delivery.ListStageEvents:input_type -> InternalApi.Delivery.ListStageEventsRequest
	24, // 31: InternalApi.Delivery.Delivery.ApproveStageEvent:input_type -> InternalApi.Delivery.ApproveStageEventRequest
	4,  // 32: InternalApi.Delivery.Delivery.CreateCanvas:output_type -> InternalApi.Delivery.CreateCanvasResponse
	6,  // 33: InternalApi.Delivery.Delivery.DescribeCanvas:output_type -> InternalApi.Delivery.DescribeCanvasResponse
	9,  // 34: InternalApi.Delivery.Delivery.CreateEventSource:output_type -> InternalApi.Delivery.CreateEventSourceResponse
	18, // 35: InternalApi.Delivery.Delivery.CreateStage:output_type -> InternalApi.Delivery.CreateStageResponse
	20, // 36: InternalApi.Delivery.Delivery.UpdateStage:output_type -> InternalApi.Delivery.UpdateStageResponse
	22, // 37: InternalApi.Delivery.Delivery.ListStageEvents:output_type -> InternalApi.Delivery.ListStageEventsResponse
	25, // 38: InternalApi.Delivery.Delivery.ApproveStageEvent:output_type -> InternalApi.Delivery.ApproveStageEventResponse
	32, // [32:39] is the sub-list for method output_type
	25, // [25:32] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_delivery_proto_init() }
func file_delivery_proto_init() {
	if File_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_proto_rawDesc), len(file_delivery_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_proto_goTypes,
		DependencyIndexes: file_delivery_proto_depIdxs,
		EnumInfos:         file_delivery_proto_enumTypes,
		MessageInfos:      file_delivery_proto_msgTypes,
	}.Build()
	File_delivery_proto = out.File
	file_delivery_proto_goTypes = nil
	file_delivery_proto_depIdxs = nil
}
