# Generated by usvc-1.13.1
# Feel free to adjust, it will not be overridden

defmodule Block.Mixfile do
  use Mix.Project

  def project do
    [
      app: :block,
      version: "0.1.0",
      elixir: "~> 1.11",
      start_permanent: Mix.env == :prod,
      deps: deps(),
      aliases: aliases()
    ]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [
      extra_applications: [:logger, :runtime_tools],
      mod: {Block.Application, []}
    ]
  end

  # Dependencies can be Hex packages:
  #
  #   {:my_dep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:my_dep, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [
      {:grpc, "~> 0.3"},
      {:log_tee, git: "https://github.com/renderedtext/log-tee.git"},
      {:uuid, "~> 1.1"},
      {:credo, "~> 1.4", only: [:dev, :test], runtime: false},
      {:httpoison, "~> 0.11"},
      {:ecto_sql, "~> 3.10"},
      {:postgrex, "~> 0.17"},
      {:jason, "~> 1.0"},
      {:watchman, github: "renderedtext/ex-watchman"},
      {:definition_validator, path: "../definition_validator"},
      {:jsx, "~> 2.9", override: true},
      {:job_matrix, path: "../job_matrix"},
      {:looper, path: "../looper"},
      {:cloak, "~> 0.5.0"},
      {:mock, "~> 0.3.0", only: :test},
      {:proto, path: "../proto"},
      {:when, github: "renderedtext/when"},
      {:grpc_mock, github: "renderedtext/grpc-mock", only: [:dev, :test]},
      {:junit_formatter, "~> 3.3", only: [:test]}
    ]
  end

  defp aliases() do
    [
      "deps.local": ["local.hex --force", "local.rebar --force"],
      "deps.setup": ["deps.local", "deps.get"],
      "ecto.reset": ["ecto.drop", "ecto.setup"],
      "ecto.setup": ["ecto.create", "ecto.migrate"],
      setup: ["deps.setup", "ecto.setup"]
    ]
  end
end
