// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.17.3
// source: semaphore/artifacts.v1.proto

package semaphore_artifacts_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateSignedURLsRequest_Type int32

const (
	GenerateSignedURLsRequest_PUSH      GenerateSignedURLsRequest_Type = 0 // gets signed URLs for Push operation without force
	GenerateSignedURLsRequest_PUSHFORCE GenerateSignedURLsRequest_Type = 1 // gets signed URLs for Push operation with force
	GenerateSignedURLsRequest_PULL      GenerateSignedURLsRequest_Type = 2 // gets signed URLs for Pull operation
	GenerateSignedURLsRequest_YANK      GenerateSignedURLsRequest_Type = 3 // gets signed URLs for Yank operation
)

// Enum value maps for GenerateSignedURLsRequest_Type.
var (
	GenerateSignedURLsRequest_Type_name = map[int32]string{
		0: "PUSH",
		1: "PUSHFORCE",
		2: "PULL",
		3: "YANK",
	}
	GenerateSignedURLsRequest_Type_value = map[string]int32{
		"PUSH":      0,
		"PUSHFORCE": 1,
		"PULL":      2,
		"YANK":      3,
	}
)

func (x GenerateSignedURLsRequest_Type) Enum() *GenerateSignedURLsRequest_Type {
	p := new(GenerateSignedURLsRequest_Type)
	*p = x
	return p
}

func (x GenerateSignedURLsRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerateSignedURLsRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_semaphore_artifacts_v1_proto_enumTypes[0].Descriptor()
}

func (GenerateSignedURLsRequest_Type) Type() protoreflect.EnumType {
	return &file_semaphore_artifacts_v1_proto_enumTypes[0]
}

func (x GenerateSignedURLsRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerateSignedURLsRequest_Type.Descriptor instead.
func (GenerateSignedURLsRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_semaphore_artifacts_v1_proto_rawDescGZIP(), []int{0, 0}
}

type SignedURL_Method int32

const (
	SignedURL_DELETE SignedURL_Method = 0 // deletes storage object or path
	SignedURL_GET    SignedURL_Method = 1 // reads storage object
	SignedURL_HEAD   SignedURL_Method = 2 // queries object or path existance
	SignedURL_PUT    SignedURL_Method = 3 // overwrites storage object
	SignedURL_POST   SignedURL_Method = 4 // concatenates to storage object
)

// Enum value maps for SignedURL_Method.
var (
	SignedURL_Method_name = map[int32]string{
		0: "DELETE",
		1: "GET",
		2: "HEAD",
		3: "PUT",
		4: "POST",
	}
	SignedURL_Method_value = map[string]int32{
		"DELETE": 0,
		"GET":    1,
		"HEAD":   2,
		"PUT":    3,
		"POST":   4,
	}
)

func (x SignedURL_Method) Enum() *SignedURL_Method {
	p := new(SignedURL_Method)
	*p = x
	return p
}

func (x SignedURL_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignedURL_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_semaphore_artifacts_v1_proto_enumTypes[1].Descriptor()
}

func (SignedURL_Method) Type() protoreflect.EnumType {
	return &file_semaphore_artifacts_v1_proto_enumTypes[1]
}

func (x SignedURL_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignedURL_Method.Descriptor instead.
func (SignedURL_Method) EnumDescriptor() ([]byte, []int) {
	return file_semaphore_artifacts_v1_proto_rawDescGZIP(), []int{2, 0}
}

// Request for Generating signed URLs with the given type.
// Contains a list of paths as the Google Cloud Storage destination or source based on the action type.
type GenerateSignedURLsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths []string                       `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	Type  GenerateSignedURLsRequest_Type `protobuf:"varint,2,opt,name=type,proto3,enum=semaphore.artifacts.v1.GenerateSignedURLsRequest_Type" json:"type,omitempty"`
}

func (x *GenerateSignedURLsRequest) Reset() {
	*x = GenerateSignedURLsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_semaphore_artifacts_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSignedURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignedURLsRequest) ProtoMessage() {}

func (x *GenerateSignedURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semaphore_artifacts_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignedURLsRequest.ProtoReflect.Descriptor instead.
func (*GenerateSignedURLsRequest) Descriptor() ([]byte, []int) {
	return file_semaphore_artifacts_v1_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateSignedURLsRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *GenerateSignedURLsRequest) GetType() GenerateSignedURLsRequest_Type {
	if x != nil {
		return x.Type
	}
	return GenerateSignedURLsRequest_PUSH
}

// Response for GenerateSignedURLs
// Contains a list of Signed URLs
type GenerateSignedURLsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URLs []*SignedURL `protobuf:"bytes,1,rep,name=URLs,proto3" json:"URLs,omitempty"`
}

func (x *GenerateSignedURLsResponse) Reset() {
	*x = GenerateSignedURLsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_semaphore_artifacts_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSignedURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignedURLsResponse) ProtoMessage() {}

func (x *GenerateSignedURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semaphore_artifacts_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignedURLsResponse.ProtoReflect.Descriptor instead.
func (*GenerateSignedURLsResponse) Descriptor() ([]byte, []int) {
	return file_semaphore_artifacts_v1_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateSignedURLsResponse) GetURLs() []*SignedURL {
	if x != nil {
		return x.URLs
	}
	return nil
}

// Contains an URL and its method type
// The path on the GCS can be parsed out of it, so it is not needed
type SignedURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URL    string           `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	Method SignedURL_Method `protobuf:"varint,2,opt,name=method,proto3,enum=semaphore.artifacts.v1.SignedURL_Method" json:"method,omitempty"`
}

func (x *SignedURL) Reset() {
	*x = SignedURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_semaphore_artifacts_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedURL) ProtoMessage() {}

func (x *SignedURL) ProtoReflect() protoreflect.Message {
	mi := &file_semaphore_artifacts_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedURL.ProtoReflect.Descriptor instead.
func (*SignedURL) Descriptor() ([]byte, []int) {
	return file_semaphore_artifacts_v1_proto_rawDescGZIP(), []int{2}
}

func (x *SignedURL) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *SignedURL) GetMethod() SignedURL_Method {
	if x != nil {
		return x.Method
	}
	return SignedURL_DELETE
}

var File_semaphore_artifacts_v1_proto protoreflect.FileDescriptor

var file_semaphore_artifacts_v1_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x73, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22, 0xb2, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x12, 0x4a, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x36, 0x2e, 0x73, 0x65, 0x6d, 0x61, 0x70,
	0x68, 0x6f, 0x72, 0x65, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x33, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x50, 0x55, 0x53, 0x48, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x55, 0x53, 0x48,
	0x46, 0x4f, 0x52, 0x43, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x55, 0x4c, 0x4c, 0x10,
	0x02, 0x12, 0x08, 0x0a, 0x04, 0x59, 0x41, 0x4e, 0x4b, 0x10, 0x03, 0x22, 0x53, 0x0a, 0x1a, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x55, 0x52, 0x4c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x65, 0x6d, 0x61, 0x70, 0x68,
	0x6f, 0x72, 0x65, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x04, 0x55, 0x52, 0x4c, 0x73,
	0x22, 0x9b, 0x01, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c,
	0x12, 0x40, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x28, 0x2e, 0x73, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x2e, 0x61, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x55, 0x52, 0x4c, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x22, 0x3a, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x45, 0x41, 0x44, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x50,
	0x55, 0x54, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x04, 0x32, 0x8f,
	0x01, 0x0a, 0x10, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x7b, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x31, 0x2e, 0x73, 0x65, 0x6d, 0x61,
	0x70, 0x68, 0x6f, 0x72, 0x65, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x73,
	0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x2e, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x64, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x27, 0x5a, 0x25, 0x2e, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x3b, 0x73, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_semaphore_artifacts_v1_proto_rawDescOnce sync.Once
	file_semaphore_artifacts_v1_proto_rawDescData = file_semaphore_artifacts_v1_proto_rawDesc
)

func file_semaphore_artifacts_v1_proto_rawDescGZIP() []byte {
	file_semaphore_artifacts_v1_proto_rawDescOnce.Do(func() {
		file_semaphore_artifacts_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_semaphore_artifacts_v1_proto_rawDescData)
	})
	return file_semaphore_artifacts_v1_proto_rawDescData
}

var file_semaphore_artifacts_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_semaphore_artifacts_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_semaphore_artifacts_v1_proto_goTypes = []any{
	(GenerateSignedURLsRequest_Type)(0), // 0: semaphore.artifacts.v1.GenerateSignedURLsRequest.Type
	(SignedURL_Method)(0),               // 1: semaphore.artifacts.v1.SignedURL.Method
	(*GenerateSignedURLsRequest)(nil),   // 2: semaphore.artifacts.v1.GenerateSignedURLsRequest
	(*GenerateSignedURLsResponse)(nil),  // 3: semaphore.artifacts.v1.GenerateSignedURLsResponse
	(*SignedURL)(nil),                   // 4: semaphore.artifacts.v1.SignedURL
}
var file_semaphore_artifacts_v1_proto_depIdxs = []int32{
	0, // 0: semaphore.artifacts.v1.GenerateSignedURLsRequest.type:type_name -> semaphore.artifacts.v1.GenerateSignedURLsRequest.Type
	4, // 1: semaphore.artifacts.v1.GenerateSignedURLsResponse.URLs:type_name -> semaphore.artifacts.v1.SignedURL
	1, // 2: semaphore.artifacts.v1.SignedURL.method:type_name -> semaphore.artifacts.v1.SignedURL.Method
	2, // 3: semaphore.artifacts.v1.ArtifactsService.GenerateSignedURLs:input_type -> semaphore.artifacts.v1.GenerateSignedURLsRequest
	3, // 4: semaphore.artifacts.v1.ArtifactsService.GenerateSignedURLs:output_type -> semaphore.artifacts.v1.GenerateSignedURLsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_semaphore_artifacts_v1_proto_init() }
func file_semaphore_artifacts_v1_proto_init() {
	if File_semaphore_artifacts_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_semaphore_artifacts_v1_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateSignedURLsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_semaphore_artifacts_v1_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateSignedURLsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_semaphore_artifacts_v1_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SignedURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_semaphore_artifacts_v1_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_semaphore_artifacts_v1_proto_goTypes,
		DependencyIndexes: file_semaphore_artifacts_v1_proto_depIdxs,
		EnumInfos:         file_semaphore_artifacts_v1_proto_enumTypes,
		MessageInfos:      file_semaphore_artifacts_v1_proto_msgTypes,
	}.Build()
	File_semaphore_artifacts_v1_proto = out.File
	file_semaphore_artifacts_v1_proto_rawDesc = nil
	file_semaphore_artifacts_v1_proto_goTypes = nil
	file_semaphore_artifacts_v1_proto_depIdxs = nil
}
