#!/usr/bin/env ruby

require "grpc"
require "grpc/health/v1/health_services_pb"

name_of_service_to_check = ARGV[0]
health_check_endpoint    = ARGV[1]

health_check_request = Grpc::Health::V1::HealthCheckRequest.new(:service => name_of_service_to_check)

stub = Grpc::Health::V1::Health::Stub.new(health_check_endpoint, :this_channel_is_insecure)
stub.check(health_check_request)
