{{- if eq .Values.global.edition "ee" }}
apiVersion: v1
kind: Service
metadata:
  name: "audit-grpc-api"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
{{- end }}
