blank_issues_enabled: false

contact_links:
  - name: Documentation
    url: https://docs.semaphoreci.com
    about: Check our documentation for answers to common questions
  - name: Community Support
    url: https://github.com/semaphoreio/semaphore/discussions
    about: Ask and answer questions in our community discussions
