source "https://rubygems.org"
git_source(:github) { |repo_name| "https://github.com/#{repo_name}.git" }

gem "bundler", ">= 1.8.4"

gem "pg", "~> 1.1"
gem "rails", ">= 8.0.4.1", "< 8.1"
gem "rack", "~> 2.2.23"
gem "sprockets-rails"

gem "excon", "~> 1.5"
gem "app"
gem "bunny"
gem "net-http" # https://github.com/ruby/net-imap/issues/16#issuecomment-803086765
gem 'net-imap', '~> 0.5.15'
# Forked grpc: patches an auth_context object leak (grpc_auth_context not
# released on the unauthenticated / no-cert early-return paths in rb_call.c).
# Built from source, so the C-core + third_party submodules are compiled at
# bundle-install time. See https://github.com/renderedtext/grpc/tree/ruby-v1.62.3-auth-context-leak-fix
gem "grpc", "~> 1.62.3", :github => "renderedtext/grpc", :branch => "ruby-v1.62.3-auth-context-leak-fix", :submodules => true
gem "googleapis-common-protos-types", "~> 1.18.0"
gem "httparty", "~> 0.24.0"
gem "httpclient"
gem "faraday", ">= 2.14.3"
gem "json"
gem "concurrent-ruby", ">= 1.3.7"
gem "crass", "~> 1.0", ">= 1.0.7"
gem "erb", ">= 6.0.4"
gem "kaminari", "~> 1.2.2"
gem "lograge"
gem "octokit"
gem "retryable"
gem "sidekiq", "7.3.10"
gem "connection_pool", "< 3" # Sidekiq 7 scheduler uses positional TimedStack#pop API
gem "sidekiq-scheduler"
gem "sidekiq-unique-jobs", "~> 8.0"
gem "puma", "~> 7.2.1"
gem "xmlrpc" # Prior to ruby 2.4 this was bundled with ruby. Required by active-support.
gem "jwt"

gem "sentry-ruby"
gem "sentry-rails"
gem "sentry-sidekiq"

gem "sprockets", "< 4"
gem "nokogiri", "~> 1.19.4"
gem "uri", "~> 1.0", ">= 1.0.4"

gem "rt-watchman", :require => "watchman", :github => "renderedtext/watchman", :ref => "74530687a232aea678b6738114c82dfc163657cd"
gem "rt-logman", :require => "logman"
gem "rt-tackle", :require => "tackle"

group :development do
  gem "spring", "~> 4.1"
  gem "spring-commands-rspec"
  gem 'brakeman', require: false
end

group :test, :development do
  gem "awesome_print"
  gem "bullet"
  gem 'pry-byebug', '~> 3.10', '>= 3.10.1'
  gem "database_cleaner"
  gem "factory_bot_rails", "< 5"
  gem "rspec-benchmark"
  gem "rspec-its"
  gem "rspec-rails", "~> 6.0"
  gem "rubocop"
  gem "rubocop-rails"
  gem "rubocop-rspec"
  gem 'rubocop-performance'
  gem 'rubocop-factory_bot', require: false
  gem "thin"
  gem "timecop"
  gem "grpc-tools"
  gem "dotenv", "~> 3.0"
end

group :test do
  gem "shoulda", "~> 4.0"
  gem "shoulda-matchers"
  gem "show_me_the_cookies"
  gem "vcr"
  gem "webmock"
  gem "rspec_junit_formatter"
end
