apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: badges-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /badges/
  rewrite: ""
  service: badges.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: connect-failure
      num_retries: 4
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: project-page-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: '*'
  prefix: /
  rewrite: ""
  service: project-page.{{ .Release.Namespace }}:80
  allow_upgrade:
  - websocket
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: 5xx
      num_retries: 4
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: project-create-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix_regex: true
  prefix: ^\/projects$
  method: POST
  rewrite: ""
  service: project-create.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: 5xx
      num_retries: 4
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: workflow-page-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /workflows/
  rewrite: ""
  service: workflow-page.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: 5xx
      num_retries: 4
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: job-page-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /jobs/
  rewrite: ""
  service: job-page.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: 5xx
      num_retries: 4
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: guard-id-http-api
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /oauth
  rewrite: ""
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: guard-id-http-api-oidc
  namespace: {{ .Release.Namespace }}
spec:
  host: "^id\\..*"
  host_regex: true
  prefix: /oidc
  rewrite: ""
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: connect-failure
      num_retries: 3
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: guard-id-http-api-blocked
  namespace: {{ .Release.Namespace }}
spec:
  host: "^id\\..*"
  host_regex: true
  prefix: /blocked
  rewrite: ""
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: connect-failure
      num_retries: 3
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: guard-id-http-api-login
  namespace: {{ .Release.Namespace }}
spec:
  host: "^id\\..*"
  host_regex: true
  prefix: /login
  rewrite: ""
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: connect-failure
      num_retries: 3
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: guard-id-http-api-logout
  namespace: {{ .Release.Namespace }}
spec:
  host: "^id\\..*"
  host_regex: true
  prefix: /logout
  rewrite: ""
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: connect-failure
      num_retries: 3
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: guard-id-http-api-signup
  namespace: {{ .Release.Namespace }}
spec:
  host: "^id\\..*"
  host_regex: true
  prefix: /signup
  rewrite: ""
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: connect-failure
      num_retries: 3
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: guard-instance-config
  namespace: {{ .Release.Namespace }}
spec:
  host: "^id\\..*"
  host_regex: true
  prefix: /github_app_manifest
  rewrite: ""
  service: guard-instance-config.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: connect-failure
      num_retries: 3
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: guard-id-http-api-root-redirect
  namespace: {{ .Release.Namespace }}
spec:
  host: "^id\\..*"
  host_regex: true
  bypass_auth: true
  prefix: /
  rewrite: ""
  service: guard-id-http-api.{{ .Release.Namespace }}:80
---
{{- if eq .Values.global.edition "ee" }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: rbac-okta-saml-http-api
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /okta/auth
  rewrite: ""
  service: rbac-okta-saml-http-api.{{ .Release.Namespace }}:4001
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: rbac-okta-scim-http-api
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /okta/scim/
  rewrite: ""
  service: rbac-okta-scim-http-api.{{ .Release.Namespace }}:4002
  precedence: 100
---
{{- end }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: hooks-receiver-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /hooks/
  rewrite: "/"
  service: hooks-receiver.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: gateway-error
      num_retries: 4
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: keycloak-realms
  namespace: {{ .Release.Namespace }}
spec:
  host: "^id\\..*"
  host_regex: true
  prefix: /realms
  rewrite: ""
  service: keycloak.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: connect-failure
      num_retries: 3
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: keycloak-resources
  namespace: {{ .Release.Namespace }}
spec:
  host: "^id\\..*"
  host_regex: true
  prefix: /resources
  rewrite: ""
  service: keycloak.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: connect-failure
      num_retries: 3
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: loghub2-public-api-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1/logs/
  rewrite: ""
  service: loghub2-public-api.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: hooks-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: "^hooks\\..*"
  host_regex: true
  prefix: /github
  rewrite: ""
  service: github-hooks.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: gateway-error
      num_retries: 4
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: public-api-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v2/
  rewrite: "/"
  service: public-api.{{ .Release.Namespace }}:4004
  timeout_ms: 30000    # increase timeout to 30s from default 3s
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: plumber-public-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/pipelines
  rewrite: "/pipelines"
  service: plumber-public.{{ .Release.Namespace }}:4004
  timeout_ms: 30000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: plumber-public-deployment-targets-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/deployment_targets
  rewrite: "/deployment_targets"
  service: plumber-public.{{ .Release.Namespace }}:4004
  timeout_ms: 30000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: plumber-public-yaml-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/yaml
  rewrite: "/yaml"
  service: plumber-public.{{ .Release.Namespace }}:4004
  timeout_ms: 30000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: plumber-public-workflow-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/plumber-workflows
  rewrite: "/workflows"
  service: plumber-public.{{ .Release.Namespace }}:4004
  timeout_ms: 30000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: plumber-public-promotions-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/promotions
  rewrite: "/promotions"
  service: plumber-public.{{ .Release.Namespace }}:4004
  timeout_ms: 5000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: plumber-public-schedules-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/schedules
  rewrite: "/schedules"
  service: plumber-public.{{ .Release.Namespace }}:4004
  timeout_ms: 5000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: plumber-public-tasks-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/tasks
  rewrite: "/tasks"
  service: plumber-public.{{ .Release.Namespace }}:4004
  timeout_ms: 5000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: plumber-public-self-hosted-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/self_hosted_agent_types
  rewrite: "/self_hosted_agent_types"
  service: plumber-public.{{ .Release.Namespace }}:4004
  timeout_ms: 5000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: plumber-public-agents-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/agents
  rewrite: "/agents"
  service: plumber-public.{{ .Release.Namespace }}:4004
  timeout_ms: 5000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: plumber-public-troubleshoot-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/troubleshoot
  rewrite: "/troubleshoot"
  service: plumber-public.{{ .Release.Namespace }}:4004
  timeout_ms: 5000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: plumber-public-artifacts-retention-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/artifacts_retention_policies
  rewrite: "/artifacts_retention_policies"
  service: plumber-public.{{ .Release.Namespace }}:4004
  timeout_ms: 5000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: plumber-public-logs-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/logs
  rewrite: "/logs"
  service: plumber-public.{{ .Release.Namespace }}:4004
  timeout_ms: 5000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: projecthub-public-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/projects
  rewrite: ""
  service: projecthub-public.{{ .Release.Namespace }}:4000
  timeout_ms: 30000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: public-api-gateway-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: ^\/api\/(v1alpha\/(workflows|dashboards|jobs|notifications)|v1beta\/secrets|v1\/(artifacts|(projects\/[a-zA-Z0-9_-]+\/secrets))).*$
  prefix_regex: true
  rewrite: ""
  service: public-api-gateway.{{ .Release.Namespace }}:80
  timeout_ms: 30000
  precedence: 100
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: secrethub-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1alpha/secrets
  rewrite: ""
  service: secrethub-http.{{ .Release.Namespace }}:4000
  precedence: 100
{{- if and (eq .Values.global.edition "ee") (index .Values "mcp-server" "enabled") }}
---
# MCP OAuth 2.1 Protected Resource Metadata (RFC 9728)
# Bypasses ExtAuth and returns OAuth discovery metadata directly
# Uses regex to preserve path suffix (e.g., /mcp) for clients that append resource path
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: mcp-oauth-metadata-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: "^mcp\\..*"
  host_regex: true
  prefix_regex: true
  prefix: /.well-known/oauth-protected-resource(.*)
  regex_rewrite:
    pattern: /.well-known/oauth-protected-resource(.*)
    substitution: /exauth/.well-known/oauth-protected-resource\1
  service: auth.{{ .Release.Namespace }}:4000
  bypass_auth: true
  precedence: 200
  timeout_ms: 5000
---
# MCP OAuth DCR endpoint - bypass auth (public client registration)
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: mcp-oauth-register-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: "^mcp\\..*"
  host_regex: true
  prefix: /mcp/oauth/register
  rewrite: /mcp/oauth/register
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  bypass_auth: true
  precedence: 210
  timeout_ms: 30000
---
# MCP OAuth Token endpoint - bypass auth (uses PKCE for security)
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: mcp-oauth-token-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: "^mcp\\..*"
  host_regex: true
  prefix: /mcp/oauth/token
  rewrite: /mcp/oauth/token
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  bypass_auth: true
  precedence: 210
  timeout_ms: 30000
---
# MCP OAuth JWKS endpoint - bypass auth (public key discovery for OIDC)
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: mcp-oauth-jwks-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: "^mcp\\..*"
  host_regex: true
  prefix: /mcp/oauth/jwks
  rewrite: /mcp/oauth/jwks
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  bypass_auth: true
  precedence: 210
  timeout_ms: 10000
---
# MCP OAuth Authorize endpoint - REQUIRE auth (user must be logged in via browser)
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: mcp-oauth-authorize-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: "^mcp\\..*"
  host_regex: true
  prefix: /mcp/oauth/authorize
  rewrite: /mcp/oauth/authorize
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  bypass_auth: false
  precedence: 210
  timeout_ms: 30000
---
# MCP OAuth Grant Selection - REQUIRE auth (user consent flow)
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: mcp-oauth-grant-selection-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: "^mcp\\..*"
  host_regex: true
  prefix: /mcp/oauth/grant-selection
  rewrite: /mcp/oauth/grant-selection
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  bypass_auth: false
  precedence: 210
  timeout_ms: 30000
---
# OAuth 2.0 Authorization Server Metadata (RFC 8414) - mcp. subdomain
# Routes to Guard which serves AS metadata for the MCP OAuth server
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: oauth-as-metadata-mapping-mcp
  namespace: {{ .Release.Namespace }}
spec:
  host: "^mcp\\..*"
  host_regex: true
  prefix: /.well-known/oauth-authorization-server
  rewrite: /mcp/oauth/.well-known/oauth-authorization-server
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  bypass_auth: true
  precedence: 200
  timeout_ms: 10000
---
# OIDC Discovery (path suffix) - for clients that use OpenID Connect style discovery
# Handles: /.well-known/openid-configuration and /.well-known/openid-configuration/mcp/oauth
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: mcp-oidc-metadata-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: "^mcp\\..*"
  host_regex: true
  prefix: /.well-known/openid-configuration
  rewrite: /mcp/oauth/.well-known/openid-configuration
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  bypass_auth: true
  precedence: 200
  timeout_ms: 10000
---
# OIDC Discovery (path insertion) - for clients using issuer path insertion
# Handles: /mcp/oauth/.well-known/openid-configuration
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: mcp-oidc-metadata-path-insertion-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: "^mcp\\..*"
  host_regex: true
  prefix: /mcp/oauth/.well-known/openid-configuration
  rewrite: /mcp/oauth/.well-known/openid-configuration
  service: guard-id-http-api.{{ .Release.Namespace }}:80
  bypass_auth: true
  precedence: 210
  timeout_ms: 10000
{{- end }}
---
{{- if eq .Values.global.edition "ee" }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: secrethub-openid-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /.well-known/
  rewrite: ""
  service: secrethub-openid-connect-http.{{ .Release.Namespace }}:5000
  precedence: 100
{{- end }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: self-hosted-hub-public-api-mapping
  namespace: {{ .Release.Namespace }}
spec:
  hostname: "*"
  prefix: /api/v1/self_hosted_agents/
  rewrite: ""
  service: self-hosted-hub-public-api.{{ .Release.Namespace }}:8000
  timeout_ms: 30000
  precedence: 100
{{- if .Values.global.artifacts.local.enabled }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: minio-artifacts-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: "^artifacts\\..*"
  host_regex: true
  prefix: /
  rewrite: ""
  service: minio-artifacts.{{ .Release.Namespace }}:9000
  timeout_ms: 30000
  bypass_auth: true
  envoy_override:
    retry_policy:
      retry_on: connect-failure
      num_retries: 3
{{- end }}
{{- if .Values.global.cache.local.enabled }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: minio-cache-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: "^cache\\..*"
  host_regex: true
  prefix: /
  rewrite: ""
  service: minio-cache.{{ .Release.Namespace }}:9000
  timeout_ms: 30000
  bypass_auth: true
  envoy_override:
    retry_policy:
      retry_on: connect-failure
      num_retries: 3
{{- end }}
{{- if .Values.global.logs.local.enabled }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: minio-logs-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: "^logs\\..*"
  host_regex: true
  prefix: /
  rewrite: ""
  service: minio-logs.{{ .Release.Namespace }}:9000
  timeout_ms: 30000
  bypass_auth: true
  envoy_override:
    retry_policy:
      retry_on: connect-failure
      num_retries: 3
{{- end }}
{{- if and (eq .Values.global.edition "ee") (index .Values "mcp-server" "enabled") }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: mcp-server-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: "^mcp\\..*"
  host_regex: true
  prefix: /
  rewrite: ""
  service: mcp-server.{{ .Release.Namespace }}:3001
  timeout_ms: 30000
  envoy_override:
    retry_policy:
      retry_on: connect-failure
      num_retries: 3
{{- end }}
