version: "3"

services:
  e2e-tests:
    build:
      context: .
      dockerfile: Dockerfile
    platform: ${PLATFORM:-linux/arm64} # Use ARM64 platform for Apple Silicon Macs
    shm_size: 2gb # Increase shared memory for Chrome
    volumes:
      - .:/app
      - ./out/screenshots:/app/out/screenshots
    environment:
      - START_WALLABY
      - WALLABY_DRIVER=chrome
      - WALLABY_CHROME_HEADLESS=true
      - MIX_ENV
      # Chrome/Chromium configuration
      - CHROME_BIN=/usr/bin/chromium-browser
      - CHROME_PATH=/usr/lib/chromium/
      # Pass Semaphore environment variables from the host
      - SEMAPHORE_API_TOKEN
      - SEMAPHORE_USER_PASSWORD
      - SEMAPHORE_BASE_DOMAIN
      - SEMAPHORE_USER_EMAIL
      - SEMAPHORE_ORGANIZATION
      - CLOUD_TEST_ENV_PREFIX
      - BASE_DOMAIN
      - GITHUB_ORGANIZATION
      - GITHUB_REPOSITORY
      - GITHUB_BRANCH
      - GOOGLE_PROJECT_NAME
      - GOOGLE_APPLICATION_CREDENTIALS
    ports:
      - "9515:9515" # ChromeDriver port
    command: >
      sh -c "chromedriver --port=9515 --verbose --whitelisted-ips='' --url-base=/wd/hub & mix test --include browser"
