apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.authentication.configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  ROOT_LOGIN: "false"
  ROOT_LOGIN_METHODS: ""
  DEFAULT_LOGIN_METHOD: oidc
  KEYCLOAK_LOGIN_PAGE: "true"
  KC_ROOT_URL: {{ printf "https://id.%s" .Values.global.domain.name }}
  KC_LOCAL_URL: http://keycloak
  KC_REALM: semaphore
  OIDC_CLIENT_ID: semaphore
  OIDC_MANAGE_CLIENT_ID: semaphore-user-management
  SESSION_COOKIE_NAME: _semaphoreci_2_0_sxmoon_session
  ENABLE_TEMPORARY_PASSWORDS: "true"
  SESSION_IDLE_TIMEOUT: "72h"
  SESSION_MAX_TIMESPAN: "720h"
  ACCESS_TOKEN_LIFESPAN: "1h"
  OFFLINE_SESSION_IDLE_TIMEOUT: "720h"
