apiVersion: v1
kind: ConfigMap
metadata:
  name: features
  namespace: {{ .Release.Namespace }}
data:
{{- if eq .Values.global.edition "ce" }}
  features.yml: |-
    activity_monitor:
      enabled: true
    artifacts:
      enabled: true
    badges:
      enabled: true
    bitbucket:
      enabled: true
    gitlab:
      enabled: true
    just_run:
      enabled: true
    max_paralellism_in_org:
      quantity: 500
    max_people_in_organization:
      quantity: 600
    max_projects_in_org:
      quantity: 10000
    parameterized_promotions:
      enabled: true
    project_level_secrets:
      enabled: true
    scheduler_hook:
      enabled: true
    self_hosted_agents:
      quantity: 1000
    toggle_skipped_blocks:
      enabled: true
    instance_git_integration:
      enabled: true
    get_started:
      enabled: true
    ui_agent_page:
      enabled: true
    new_project_onboarding:
      enabled: true
    advanced_deployment_targets:
      enabled: true
{{- else }}
  features.yml: |-
    advanced_deployment_targets:
      enabled: true
    audit_logs:
      enabled: true
    audit_streaming:
      enabled: true
    activity_monitor:
      enabled: true
    artifacts:
      enabled: true
    badges:
      enabled: true
    bitbucket:
      enabled: true
    gitlab:
      enabled: true
    deployment_targets:
      enabled: true
    ip_allow_list:
      enabled: true
    just_run:
      enabled: true
    max_paralellism_in_org:
      quantity: 500
    max_people_in_organization:
      quantity: 600
    max_projects_in_org:
      quantity: 10000
    multiple_organizations:
      enabled: false
    okta:
      enabled: true
    open_id_connect:
      enabled: true
    open_id_connect_aws_tags:
      enabled: true
    organization_health:
      enabled: true
    parameterized_promotions:
      enabled: true
    permission_patrol:
      enabled: true
    pipeline_summaries:
      enabled: true
    pre_flight_checks:
      enabled: true
    project_level_roles:
      enabled: true
    project_level_secrets:
      enabled: true
    rbac__groups:
      enabled: true
    rbac__saml:
      enabled: true
    rbac__custom_roles:
      enabled: true
    rbac__project_roles:
      enabled: true
    restrict_job_ssh_access:
      enabled: true
    scheduler_hook:
      enabled: true
    secrets_access_policy:
      enabled: true
    secrets_exposed_content:
      enabled: false
    self_hosted_agents:
      quantity: 1000
    superjerry_tests:
      enabled: false
    test_explorer:
      enabled: false
    test_results:
      enabled: false
    toggle_skipped_blocks:
      enabled: true
    instance_git_integration:
      enabled: true
    get_started:
      enabled: true
    ui_agent_page:
      enabled: true
    new_project_onboarding:
      enabled: true
{{- end }}