apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.internalApi.configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  INTERNAL_API_URL_AGENTHUB: self-hosted-hub-internal-api:50051
  INTERNAL_API_URL_ARTIFACTHUB: artifacthub-internal-grpc-api:50051
  INTERNAL_API_URL_ARTIFACTHUB_USAGE: artifacthub-usage:50051
  INTERNAL_API_URL_AUDIT: audit-grpc-api:50051
  INTERNAL_API_URL_AUTHENTICATION: guard-authentication-api:50051
  INTERNAL_API_URL_BILLING: billing:50051
  INTERNAL_API_URL_BRANCH: branchhub-grpc:50051
  INTERNAL_API_URL_CACHEHUB: cachehub-grpc:50051
  INTERNAL_API_URL_CHMURA: chmura-internal-api-canary:50051
  INTERNAL_API_URL_DASHBOARDHUB: dashboards-v1alpha-public-grpc-api:50051
  INTERNAL_API_URL_FEATURE: feature-hub:50052
  INTERNAL_API_URL_GOFER: gofer:50055
  INTERNAL_API_URL_GUARD: guard:50051
  INTERNAL_API_URL_HOOKS: hooks-processor-api:50050
  INTERNAL_API_URL_INSTANCE_CONFIG: guard-instance-config:50051
  INTERNAL_API_URL_JOB: zebra-job-api:50051
  INTERNAL_API_URL_LICENSE_CHECKER: license-checker:50051
  INTERNAL_API_URL_LOGHUB2: loghub2-internal-api:50051
  INTERNAL_API_URL_NOTIFICATION: notifications-v1alpha-public-grpc-api:50051
  INTERNAL_API_URL_ORGANIZATION: guard-organization-api:50051
  INTERNAL_API_URL_PFC: pre-flight-checks-hub:50051
  INTERNAL_API_URL_PLUMBER: ppl:50053
  INTERNAL_API_URL_PROJECT: projecthub-grpc:50051
  INTERNAL_API_URL_REPOHUB: repohub-internal-api:50051
  INTERNAL_API_URL_REPOSITORY: repository-hub:50051
  INTERNAL_API_URL_REPOSITORY_INTEGRATOR: github-hooks-repo-proxy-api:50051
  INTERNAL_API_URL_REPO_PROXY: github-hooks-repo-proxy-api:50051
  INTERNAL_API_URL_SCHEDULER: periodic-scheduler:50050
  INTERNAL_API_URL_SCOUTER: scouter-api:50051
  INTERNAL_API_URL_SECRETHUB: secrethub-grpc:50051
  INTERNAL_API_URL_SELFHOSTEDHUB: self-hosted-hub-internal-api:50051
  INTERNAL_API_URL_SUPERJERRY: superjerry-api:50051
  INTERNAL_API_URL_TASK: zebra-task-api:50051
  INTERNAL_API_URL_USER: guard-user-api:50051
  INTERNAL_API_URL_VELOCITY: velocity-hub:50051
  INTERNAL_API_URL_SERVICE_ACCOUNT: guard-service-account-api:50051
{{- if eq .Values.global.edition "ce" }}
  INTERNAL_API_URL_RBAC: rbac:50051
  INTERNAL_API_URL_OKTA: guard-okta-internal-api:50051
{{- else if .Values.global.edition }}
  INTERNAL_API_URL_GROUPS: rbac-groups-api:50051
  INTERNAL_API_URL_OKTA: rbac-okta-api:50051
  INTERNAL_API_URL_RBAC: rbac-ee-api:50051
{{- end }}
