apiVersion: v1
kind: ConfigMap
metadata:
  name: permissions
  namespace: {{ .Release.Namespace }}
data:
{{- if eq .Values.global.edition "ce" }}
  permissions.yaml: |-
    permissions:
      organization:
        - name: "organization.delete"
          description: "Delete the organization."
        - name: "organization.view"
          description: "Access to the organization. This permission is needed to access any page within the organization domain."
        - name: "organization.activity_monitor.view"
          description: "View organization's activity monitor."
        - name: "organization.projects.create"
          description: "Create a new project within the organization."
        - name: "organization.people.view"
          description: "View list of people within the organization, together with the roles they have."
        - name: "organization.people.invite"
          description: "Invite new people to the organization."
        - name: "organization.people.manage"
          description: "Remove people from the organization, or change their roles within the organization."
        - name: "organization.change_owner"
          description: "Change the owner of the organization."
        - name: "organization.self_hosted_agents.view"
          description: "View the list of self-hosted agents within the organization."
        - name: "organization.self_hosted_agents.manage"
          description: "Manage self-hosted agents within the organization."
        - name: "organization.general_settings.view"
          description: "View general settings for the organization."
        - name: "organization.general_settings.manage"
          description: "Manage general settings of the organization."
        - name: "organization.secrets.view"
          description: "View secrets within the organization."
        - name: "organization.secrets.manage"
          description: "Manage secrets within the organization."
        - name: "organization.notifications.view"
          description: "View organization notification settings."
        - name: "organization.notifications.manage"
          description: "Modify organization notification settings."
        - name: "organization.pre_flight_checks.view"
          description: "View pre-flight checks within the organization."
        - name: "organization.pre_flight_checks.manage"
          description: "Modify pre-flight checks within the organization."
        - name: "organization.dashboards.view"
          description: "View the existing dashboards within the organization."
        - name: "organization.dashboards.manage"
          description: "Create new dashboard views."
        - name: "organization.instance_git_integration.manage"
          description: "Manage the instance Git integration settings."
      project:
        - name: "project.view"
          description: "Access the project. This permission is needed to see any page within the project."
        - name: "project.delete"
          description: "Delete the project."
        - name: "project.access.view"
          description: "View people, groups and bots that have acces to the project."
        - name: "project.access.manage"
          description: "Manage who has access to the project."
        - name: "project.secrets.view"
          description: "View existing secrets related to the project."
        - name: "project.secrets.manage"
          description: "Manage project secrets."
        - name: "project.notifications.view"
          description: "View project notifications."
        - name: "project.notifications.manage"
          description: "Manage project notifications."
        - name: "project.insights.view"
          description: "View insights and analytics for the project."
        - name: "project.insights.manage"
          description: "Change how insights for the project are calculated."
        - name: "project.flaky_tests.view"
          description: "View the flaky tests page."
        - name: "project.flaky_tests.manage"
          description: "Create new filters and notifications for flaky tests."
        - name: "project.artifacts.view"
          description: "Access the artifacts on the project, workflow and job level."
        - name: "project.artifacts.delete"
          description: "Remove individual artifacts."
        - name: "project.artifacts.view_settings"
          description: "View artifact settings."
        - name: "project.artifacts.modify_settings"
          description: "Modify artifact settings, such as retention policy."
        - name: "project.scheduler.view"
          description: "View tasks within the project."
        - name: "project.scheduler.manage"
          description: "Modify project tasks."
        - name: "project.scheduler.run_manually"
          description: "Trigger manual runs of any existing tasks."
        - name: "project.general_settings.view"
          description: "View general settings for the project."
        - name: "project.general_settings.manage"
          description: "Modify general settings for the project."
        - name: "project.repository_info.view"
          description: "View git repository information."
        - name: "project.repository_info.manage"
          description: "Modify git repository information."
        - name: "project.pre_flight_checks.view"
          description: "View pre-flight checks for the project."
        - name: "project.pre_flight_checks.manage"
          description: "Modify pre-flight checks for the project."
        - name: "project.workflow.manage"
          description: "Change workflow definition (jobs that will run within the workflow)."
        - name: "project.job.rerun"
          description: "Manually rerun jobs or entire workflows"
        - name: "project.job.stop"
          description: "Manually stop running jobs or workflows."
        - name: "project.job.attach"
          description: "SSH into the running job, or start a debug session."
{{- end }}
{{- if eq .Values.global.edition "ee" }}
  permissions.yaml: |-
    permissions:
      organization:
        - name: "organization.okta.view"
          description: "View Okta integration settings for the organization."
        - name: "organization.okta.manage"
          description: "Modify existing Okta integrations, or create a new one."
        - name: "organization.contact_support"
          description: "Contact support on behalf of the organization."
        - name: "organization.delete"
          description: "Delete the organization."
        - name: "organization.view"
          description: "Access to the organization. This permission is needed to access any page within the organization domain."
        - name: "organization.secrets_policy_settings.manage"
          description: "Manage secrets policy settings within the organization."
        - name: "organization.secrets_policy_settings.view"
          description: "View existing secrets policy settings."
        - name: "organization.activity_monitor.view"
          description: "View organization's activity monitor."
        - name: "organization.projects.create"
          description: "Create a new project within the organization."
        - name: "organization.audit_logs.view"
          description: "View audit logs."
        - name: "organization.audit_logs.manage"
          description: "Manage audit log settings for the organization (such as log streams)."
        - name: "organization.people.view"
          description: "View list of people within the organization, together with the roles they have."
        - name: "organization.people.invite"
          description: "Invite new people to the organization."
        - name: "organization.people.manage"
          description: "Remove people from the organization, or change their roles within the organization."
        - name: "organization.change_owner"
          description: "Change the owner of the organization."
        - name: "organization.groups.view"
          description: "View user groups within the organization."
        - name: "organization.groups.manage"
          description: "Manage groups within the organization and modify group members."
        - name: "organization.custom_roles.view"
          description: "View roles within the organization and permissions they carry."
        - name: "organization.custom_roles.manage"
          description: "Modify definition of roles within the organization."
        - name: "organization.self_hosted_agents.view"
          description: "View the list of self-hosted agents within the organization."
        - name: "organization.self_hosted_agents.manage"
          description: "Manage self-hosted agents within the organization."
        - name: "organization.general_settings.view"
          description: "View general settings for the organization."
        - name: "organization.general_settings.manage"
          description: "Manage general settings of the organization."
        - name: "organization.secrets.view"
          description: "View secrets within the organization."
        - name: "organization.secrets.manage"
          description: "Manage secrets within the organization."
        - name: "organization.ip_allow_list.view"
          description: "View the IP allow list."
        - name: "organization.ip_allow_list.manage"
          description: "Modify the IP allow list for the organization."
        - name: "organization.notifications.view"
          description: "View organization notification settings."
        - name: "organization.notifications.manage"
          description: "Modify organization notification settings."
        - name: "organization.pre_flight_checks.view"
          description: "View pre-flight checks within the organization."
        - name: "organization.pre_flight_checks.manage"
          description: "Modify pre-flight checks within the organization."
        - name: "organization.plans_and_billing.view"
          description: "Access the billing page."
        - name: "organization.plans_and_billing.manage"
          description: "Modify billing information or subscription plan."
        - name: "organization.dashboards.view"
          description: "View the existing dashboards within the organization."
        - name: "organization.dashboards.manage"
          description: "Create new dashboard views."
        - name: "organization.instance_git_integration.manage"
          description: "Manage the instance Git integration settings."
      project:
        - name: "project.view"
          description: "Access the project. This permission is needed to see any page within the project."
        - name: "project.delete"
          description: "Delete the project."
        - name: "project.access.view"
          description: "View people, groups and bots that have acces to the project."
        - name: "project.access.manage"
          description: "Manage who has access to the project."
        - name: "project.secrets.view"
          description: "View existing secrets related to the project."
        - name: "project.secrets.manage"
          description: "Manage project secrets."
        - name: "project.notifications.view"
          description: "View project notifications."
        - name: "project.notifications.manage"
          description: "Manage project notifications."
        - name: "project.insights.view"
          description: "View insights and analytics for the project."
        - name: "project.insights.manage"
          description: "Change how insights for the project are calculated."
        - name: "project.flaky_tests.view"
          description: "View the flaky tests page."
        - name: "project.flaky_tests.manage"
          description: "Create new filters and notifications for flaky tests."
        - name: "project.artifacts.view"
          description: "Access the artifacts on the project, workflow and job level."
        - name: "project.artifacts.delete"
          description: "Remove individual artifacts."
        - name: "project.artifacts.view_settings"
          description: "View artifact settings."
        - name: "project.artifacts.modify_settings"
          description: "Modify artifact settings, such as retention policy."
        - name: "project.scheduler.view"
          description: "View tasks within the project."
        - name: "project.scheduler.manage"
          description: "Modify project tasks."
        - name: "project.scheduler.run_manually"
          description: "Trigger manual runs of any existing tasks."
        - name: "project.general_settings.view"
          description: "View general settings for the project."
        - name: "project.general_settings.manage"
          description: "Modify general settings for the project."
        - name: "project.repository_info.view"
          description: "View git repository information."
        - name: "project.repository_info.manage"
          description: "Modify git repository information."
        - name: "project.deployment_targets.view"
          description: "View existing deployment targets."
        - name: "project.deployment_targets.manage"
          description: "Manage deployment targets."
        - name: "project.pre_flight_checks.view"
          description: "View pre-flight checks for the project."
        - name: "project.pre_flight_checks.manage"
          description: "Modify pre-flight checks for the project."
        - name: "project.workflow.manage"
          description: "Change workflow definition (jobs that will run within the workflow)."
        - name: "project.job.rerun"
          description: "Manually rerun jobs or entire workflows"
        - name: "project.job.stop"
          description: "Manually stop running jobs or workflows."
        - name: "project.job.attach"
          description: "SSH into the running job, or start a debug session."
{{- end }}