apiVersion: v1
kind: ConfigMap
metadata:
  name: roles
  namespace: {{ .Release.Namespace }}
data:
{{- if eq .Values.global.edition "ce" }}
  roles.yaml: |-
    roles:
      org_scope:
        - name: "Owner"
          description: "Owners have access to all functionalities within the organization and any of its projects. They cannot be removed from the organization."
          maps_to: "Admin"
          permissions:
            - "organization.delete"
            - "organization.view"
            - "organization.activity_monitor.view"
            - "organization.projects.create"
            - "organization.people.view"
            - "organization.people.invite"
            - "organization.people.manage"
            - "organization.change_owner"
            - "organization.self_hosted_agents.view"
            - "organization.self_hosted_agents.manage"
            - "organization.general_settings.view"
            - "organization.general_settings.manage"
            - "organization.secrets.view"
            - "organization.secrets.manage"
            - "organization.notifications.view"
            - "organization.notifications.manage"
            - "organization.pre_flight_checks.view"
            - "organization.pre_flight_checks.manage"
            - "organization.dashboards.view"
            - "organization.dashboards.manage"
            - "organization.instance_git_integration.manage"
        - name: "Admin"
          description: "Admins can modify settings within the organization or any of its projects. However, they do not have access to billing information, and they cannot change general organization details, such as the organization name and URL."
          maps_to: "Admin"
          permissions:
            - "organization.view"
            - "organization.activity_monitor.view"
            - "organization.projects.create"
            - "organization.people.view"
            - "organization.people.invite"
            - "organization.people.manage"
            - "organization.self_hosted_agents.view"
            - "organization.self_hosted_agents.manage"
            - "organization.general_settings.view"
            - "organization.general_settings.manage"
            - "organization.secrets.view"
            - "organization.secrets.manage"
            - "organization.notifications.view"
            - "organization.notifications.manage"
            - "organization.pre_flight_checks.view"
            - "organization.pre_flight_checks.manage"
            - "organization.dashboards.manage"
            - "organization.dashboards.view"
            - "organization.dashboards.manage"
            - "project.delete"
        - name: "Member"
          description: "Members can access the organization's homepage and the projects they are assigned to. However, they are not able to modify any settings."
          permissions:
            - "organization.view"
            - "organization.activity_monitor.view"
            - "organization.projects.create"
            - "organization.self_hosted_agents.view"
            - "organization.self_hosted_agents.manage"
            - "organization.secrets.view"
            - "organization.secrets.manage"
            - "organization.notifications.view"
            - "organization.notifications.manage"
            - "organization.dashboards.manage"
            - "organization.dashboards.view"
      project_scope:
        - name: "Admin"
          description: "Admins have the authority to modify any setting within the projects, including the ability to add new individuals, remove them, or even delete the entire project."
          permissions:
            - "project.access.manage"
            - "project.secrets.view"
            - "project.secrets.manage"
            - "project.notifications.view"
            - "project.notifications.manage"
            - "project.view"
            - "project.insights.view"
            - "project.insights.manage"
            - "project.artifacts.view"
            - "project.scheduler.view"
            - "project.delete"
            - "project.artifacts.delete"
            - "project.artifacts.view_settings"
            - "project.flaky_tests.view"
            - "project.flaky_tests.manage"
            - "project.artifacts.modify_settings"
            - "project.scheduler.manage"
            - "project.scheduler.run_manually"
            - "project.access.view"
            - "project.general_settings.view"
            - "project.general_settings.manage"
            - "project.repository_info.view"
            - "project.repository_info.manage"
            - "project.pre_flight_checks.view"
            - "project.pre_flight_checks.manage"
            - "project.workflow.manage"
            - "project.job.rerun"
            - "project.job.stop"
            - "project.job.attach"
        - name: "Contributor"
          description: "Contributors can manually run, stop, or edit workflows. They can view job logs, start debug sessions and SSH into the machines. Additionally, they can view secrets, schedulers, and notifications used within the projects but can't modify them."
          permissions:
            - "project.general_settings.manage"
            - "project.secrets.view"
            - "project.secrets.manage"
            - "project.notifications.view"
            - "project.notifications.manage"
            - "project.view"
            - "project.insights.view"
            - "project.insights.manage"
            - "project.artifacts.view"
            - "project.scheduler.view"
            - "project.delete"
            - "project.flaky_tests.view"
            - "project.flaky_tests.manage"
            - "project.artifacts.delete"
            - "project.artifacts.view_settings"
            - "project.artifacts.modify_settings"
            - "project.scheduler.manage"
            - "project.scheduler.run_manually"
            - "project.access.view"
            - "project.general_settings.view"
            - "project.repository_info.view"
            - "project.repository_info.manage"
            - "project.pre_flight_checks.view"
            - "project.pre_flight_checks.manage"
            - "project.workflow.manage"
            - "project.job.rerun"
            - "project.job.stop"
            - "project.job.attach"
        - name: "Reader"
          description: "Readers can access the project page, view workflows, their results, and job logs. However, they cannot make any modifications within the project."
          permissions:
            - "project.notifications.view"
            - "project.view"
            - "project.access.view"
            - "project.insights.view"
            - "project.flaky_tests.view"
            - "project.scheduler.view"
            - "project.general_settings.view"
            - "project.repository_info.view"
            - "project.pre_flight_checks.view"
            - "project.artifacts.view"
      repo_to_role_mappings:
        admin: "Contributor"
        push: "Contributor"
        pull: "Reader"
{{- end }}
{{- if eq .Values.global.edition "ee" }}
  roles.yaml: |-
    roles:
      org_scope:
        - name: "Owner"
          description: "Owners have access to all functionalities within the organization and any of its projects. They cannot be removed from the organization."
          maps_to: "Admin"
          permissions:
            - "organization.okta.view"
            - "organization.okta.manage"
            - "organization.contact_support"
            - "organization.secrets_policy_settings.manage"
            - "organization.secrets_policy_settings.view"
            - "organization.delete"
            - "organization.view"
            - "organization.activity_monitor.view"
            - "organization.projects.create"
            - "organization.audit_logs.view"
            - "organization.audit_logs.manage"
            - "organization.people.view"
            - "organization.people.invite"
            - "organization.people.manage"
            - "organization.groups.view"
            - "organization.groups.manage"
            - "organization.change_owner"
            - "organization.self_hosted_agents.view"
            - "organization.self_hosted_agents.manage"
            - "organization.general_settings.view"
            - "organization.general_settings.manage"
            - "organization.secrets.view"
            - "organization.secrets.manage"
            - "organization.notifications.view"
            - "organization.notifications.manage"
            - "organization.ip_allow_list.view"
            - "organization.ip_allow_list.manage"
            - "organization.pre_flight_checks.view"
            - "organization.pre_flight_checks.manage"
            - "organization.plans_and_billing.view"
            - "organization.plans_and_billing.manage"
            - "organization.custom_roles.manage"
            - "organization.custom_roles.view"
            - "organization.dashboards.view"
            - "organization.dashboards.manage"
            - "organization.instance_git_integration.manage"
        - name: "Admin"
          description: "Admins can modify settings within the organization or any of its projects. However, they do not have access to billing information, and they cannot change general organization details, such as the organization name and URL."
          maps_to: "Admin"
          permissions:
            - "organization.okta.view"
            - "organization.okta.manage"
            - "organization.contact_support"
            - "organization.secrets_policy_settings.manage"
            - "organization.secrets_policy_settings.view"
            - "organization.view"
            - "organization.activity_monitor.view"
            - "organization.projects.create"
            - "organization.audit_logs.view"
            - "organization.audit_logs.manage"
            - "organization.people.view"
            - "organization.people.invite"
            - "organization.people.manage"
            - "organization.groups.view"
            - "organization.groups.manage"
            - "organization.self_hosted_agents.view"
            - "organization.self_hosted_agents.manage"
            - "organization.general_settings.view"
            - "organization.general_settings.manage"
            - "organization.secrets.view"
            - "organization.secrets.manage"
            - "organization.notifications.view"
            - "organization.notifications.manage"
            - "organization.ip_allow_list.view"
            - "organization.ip_allow_list.manage"
            - "organization.pre_flight_checks.view"
            - "organization.pre_flight_checks.manage"
            - "organization.plans_and_billing.view"
            - "organization.plans_and_billing.manage"
            - "organization.dashboards.manage"
            - "organization.custom_roles.view"
            - "organization.dashboards.view"
            - "organization.dashboards.manage"
            - "project.delete"
        - name: "Member"
          description: "Members can access the organization's homepage and the projects they are assigned to. However, they are not able to modify any settings."
          permissions:
            - "organization.contact_support"
            - "organization.secrets_policy_settings.view"
            - "organization.view"
            - "organization.activity_monitor.view"
            - "organization.projects.create"
            - "organization.self_hosted_agents.view"
            - "organization.self_hosted_agents.manage"
            - "organization.groups.view"
            - "organization.secrets.view"
            - "organization.secrets.manage"
            - "organization.notifications.view"
            - "organization.notifications.manage"
            - "organization.dashboards.manage"
            - "organization.dashboards.view"
      project_scope:
        - name: "Admin"
          description: "Admins have the authority to modify any setting within the projects, including the ability to add new individuals, remove them, or even delete the entire project."
          permissions:
            - "project.access.manage"
            - "project.secrets.view"
            - "project.secrets.manage"
            - "project.notifications.view"
            - "project.notifications.manage"
            - "project.view"
            - "project.insights.view"
            - "project.insights.manage"
            - "project.artifacts.view"
            - "project.scheduler.view"
            - "project.delete"
            - "project.artifacts.delete"
            - "project.artifacts.view_settings"
            - "project.deployment_targets.view"
            - "project.deployment_targets.manage"
            - "project.flaky_tests.view"
            - "project.flaky_tests.manage"
            - "project.artifacts.modify_settings"
            - "project.scheduler.manage"
            - "project.scheduler.run_manually"
            - "project.access.view"
            - "project.general_settings.view"
            - "project.general_settings.manage"
            - "project.repository_info.view"
            - "project.repository_info.manage"
            - "project.pre_flight_checks.view"
            - "project.pre_flight_checks.manage"
            - "project.workflow.manage"
            - "project.job.rerun"
            - "project.job.stop"
            - "project.job.attach"
        - name: "Contributor"
          description: "Contributors can manually run, stop, or edit workflows. They can view job logs, start debug sessions and SSH into the machines. Additionally, they can view secrets, schedulers, and notifications used within the projects but can't modify them."
          permissions:
            - "project.general_settings.manage"
            - "project.secrets.view"
            - "project.secrets.manage"
            - "project.notifications.view"
            - "project.notifications.manage"
            - "project.view"
            - "project.insights.view"
            - "project.insights.manage"
            - "project.artifacts.view"
            - "project.scheduler.view"
            - "project.deployment_targets.view"
            - "project.delete"
            - "project.flaky_tests.view"
            - "project.flaky_tests.manage"
            - "project.artifacts.delete"
            - "project.artifacts.view_settings"
            - "project.artifacts.modify_settings"
            - "project.scheduler.manage"
            - "project.scheduler.run_manually"
            - "project.access.view"
            - "project.general_settings.view"
            - "project.repository_info.view"
            - "project.repository_info.manage"
            - "project.pre_flight_checks.view"
            - "project.pre_flight_checks.manage"
            - "project.workflow.manage"
            - "project.job.rerun"
            - "project.job.stop"
            - "project.job.attach"
        - name: "Reader"
          description: "Readers can access the project page, view workflows, their results, and job logs. However, they cannot make any modifications within the project."
          permissions:
            - "project.notifications.view"
            - "project.view"
            - "project.access.view"
            - "project.insights.view"
            - "project.flaky_tests.view"
            - "project.deployment_targets.view"
            - "project.scheduler.view"
            - "project.general_settings.view"
            - "project.repository_info.view"
            - "project.pre_flight_checks.view"
            - "project.artifacts.view"
      repo_to_role_mappings:
        admin: "Contributor"
        push: "Contributor"
        pull: "Reader"
{{- end }}
