{{- $chartName := regexReplaceAll "_" .Chart.Name "-" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $chartName }}-sidekiq"
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.sidekiq.replicas }}
  selector:
    matchLabels:
      app: "{{ $chartName }}-sidekiq"
  template:
    metadata:
      name: "{{ $chartName }}-sidekiq"
      labels:
        app: "{{ $chartName }}-sidekiq"
        product: semaphoreci
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
        - name: {{ . }}
{{- end }}
{{- end }}
      automountServiceAccountToken: false
      initContainers:
{{ include "initContainers.all" . | indent 8 }}
      containers:
        - name: "{{ $chartName }}-sidekiq"
          image: "{{ .Values.global.image.registry }}/{{ .Values.image }}:{{ .Values.imageTag }}"
          command: ["bash", "-c"]
          args: ["bundle exec rails db:create db:migrate && bundle exec sidekiq -c 5 -t 10 -e $RAILS_ENV -C /app/config/sidekiq.yml"]
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: internal-api-urls
          env:
            - name: RACK_ENV
              value: production
            - name: RAILS_ENV
              value: production

            - name: SEMAPHORE_EDITION
              value: {{ .Values.global.edition }}

            - name: SECRET_KEY_BASE
              valueFrom: { secretKeyRef: { name: {{ include "secrets.authentication.name" . }}, key: SESSION_SECRET_KEY_BASE } }

            - name: BASE_DOMAIN
              valueFrom: { configMapKeyRef: { name: {{ .Values.global.domain.configMapName }}, key: BASE_DOMAIN } }
            - name: HOOKS_HOST
              value: "hooks.$(BASE_DOMAIN)"
            - name: HOST
              value: "id.$(BASE_DOMAIN)"

            - name: POSTGRES_DB_SSL
              value: {{ .Values.global.database.ssl | quote }}
            - name: DB_POOL_SIZE
              value: {{ .Values.sidekiq.dbPoolSize | quote }}
            - name: POSTGRES_DB_NAME
              value: {{ .Values.db.name | quote }}
            {{- include "env.db.elixir" . | indent 12 }}
            - name: PGAPPNAME
              value: sidekiq

            - name: AMQP_URL
              valueFrom: { secretKeyRef: { name: {{ .Values.global.rabbitmq.secretName }}, key: amqp-url }}

            - name: REDIS_HOST
              valueFrom: { secretKeyRef: { name: {{ .Values.global.redis.secretName }}, key: host }}
            - name: REDIS_PORT
              valueFrom: { secretKeyRef: { name: {{ .Values.global.redis.secretName }}, key: port }}
            - name: REDIS_USERNAME
              valueFrom: { secretKeyRef: { name: {{ .Values.global.redis.secretName }}, key: username }}
            - name: REDIS_SIDEKIQ_PASSWORD
              valueFrom: { secretKeyRef: { name: {{ .Values.global.redis.secretName }}, key: password }}
            - name: REDIS_SIDEKIQ_URL
              value: "redis://$(REDIS_USERNAME)@$(REDIS_HOST):$(REDIS_PORT)"

{{- if .Values.global.statsd.enabled }}
            - name: METRICS_NAMESPACE
              value: {{ .Values.global.statsd.metricsNamespace }}
{{- end }}


{{- if .Values.sidekiq.resources }}
          resources:
{{ toYaml .Values.sidekiq.resources | indent 13 }}
{{- end }}

{{- if .Values.global.statsd.enabled }}
        - name: "{{ $chartName }}-statsd"
          image: "{{ .Values.global.image.registry }}/{{ .Values.global.statsd.image }}:{{ .Values.global.statsd.imageTag }}"
          env:
            - name: FLUSH_INTERVAL
              value: "60000"
            - name: GRAPHITE_HOST
              value: {{ .Values.global.statsd.graphiteHost }}
{{- if .Values.statsd.resources }}
          resources:
{{ toYaml .Values.statsd.resources | indent 13 }}
{{- end }}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
{{- end }}
