apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-bucketcleaner-worker
spec:
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}-bucketcleaner-worker"
  replicas: {{ .Values.bucketCleanerWorker.replicas }}
  template:
    metadata:
      name: {{ .Chart.Name }}-bucketcleaner-worker
      labels:
        app: {{ .Chart.Name }}-bucketcleaner-worker
        product: semaphoreci
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
        - name: {{ . }}
{{- end }}
{{- end }}
      automountServiceAccountToken: false
      initContainers:
{{ include "initContainers.all" . | indent 8 }}
      containers:
        - name: {{ .Chart.Name }}-bucketcleaner-worker
          image: "{{ .Values.global.image.registry }}/{{ .Values.image }}:{{ .Values.imageTag }}"
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          envFrom:
            - secretRef:
                name: {{ .Values.global.artifacts.secretName }}
          env:
            {{- include "env.db.go" . | indent 12 }}
            - name: START_BUCKETCLEANER_WORKER
              value: "yes"
            - name: BUCKETCLEANER_WORKER_NUMBER_OF_PAGES_TO_PROCESS_IN_ONE_GO
              value: "10"
            - name: LOG_LEVEL
              value: "INFO"
            - name: POSTGRES_DB_SSL
              value: {{ .Values.global.database.ssl | quote }}
            - name: DB_NAME
              value: {{ .Values.db.name | quote }}
            - name: APPLICATION_NAME
              value: "{{ .Chart.Name }}-bucketcleaner-worker"
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.rabbitmq.secretName }}
                  key: amqp-url
{{- if .Values.global.statsd.enabled }}
            - name: METRICS_NAMESPACE
              value: {{ .Values.global.statsd.metricsNamespace }}
{{- end }}
{{- if .Values.bucketCleanerWorker.resources }}
          resources:
{{ toYaml .Values.bucketCleanerWorker.resources | indent 13 }}
{{- end }}

{{- if .Values.global.statsd.enabled }}
        - name: {{ .Chart.Name }}-statsd
          image: "{{ .Values.global.image.registry }}/{{ .Values.global.statsd.image }}:{{ .Values.global.statsd.imageTag }}"
          env:
            - name: FLUSH_INTERVAL
              value: "60000"
            - name: GRAPHITE_HOST
              value: {{ .Values.global.statsd.graphiteHost }}
{{- if .Values.statsd.resources }}
          resources:
{{ toYaml .Values.statsd.resources | indent 13 }}
{{- end }}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
{{- end }}
