{{- if eq .Values.global.edition "ee" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-worker
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}-worker"
  replicas: {{ .Values.worker.replicas }}
  template:
    metadata:
      name: "{{ .Chart.Name }}-worker"
      labels:
        app: "{{ .Chart.Name }}-worker"
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.global.image.registry }}/{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: grpc-port
              containerPort: 50051
          env:
            {{- include "env.db.go" . | indent 12 }}
            - name: START_INTERNAL_API
              value: 'yes'
            - name: START_PIPELINE_DONE_COLLECTOR
              value: 'yes'
            - name: POSTGRES_DB_SSL
              value: {{ .Values.global.database.ssl | quote }}
            - name: DB_NAME
              value: velocity
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.rabbitmq.secretName }}
                  key: amqp-url
{{- if .Values.global.statsd.enabled }}
            - name: METRICS_NAMESPACE
              value: {{ .Values.global.statsd.metricsNamespace }}
{{- end }}

{{- if .Values.worker.resources }}
          resources:
{{ toYaml .Values.worker.resources | indent 13 }}
{{- end }}

          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 5
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10

{{- if .Values.global.statsd.enabled }}
        - name: {{ .Chart.Name }}-statsd
          image: "{{ .Values.global.image.registry }}/{{ .Values.global.statsd.image }}:{{ .Values.global.statsd.imageTag }}"
          env:
            - name: FLUSH_INTERVAL
              value: "60000"
            - name: GRAPHITE_HOST
              value: {{ .Values.global.statsd.graphiteHost }}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
{{- if .Values.statsd.resources }}
          resources:
{{ toYaml .Values.statsd.resources | indent 13 }}
{{- end }}
{{- end }}
{{- end }}
