import * as types from "../types";
import * as toolbox from "js/toolbox";

interface GroupTooltipProps {
  group: types.Spendings.Group;
}

export const GroupTooltip = (props: GroupTooltipProps) => {
  return (
    <toolbox.Popover
      anchor={<toolbox.Asset path="images/icn-info-15.svg" className={`pointer`}/>}
      content={<GroupDescription group={props.group}/>}
    />
  );
};

const GroupDescription = ({ group }: { group: types.Spendings.Group }) => {
  switch (group.type) {
    case types.Spendings.GroupType.MachineCapacity:
      return (
        <div className="f5">
          <div className="mb2">
            <div className="b">What is this?</div>
            <div className="mb2">
              Machine capacity refers to the maximum number of Semaphore cloud machines that you can use concurrently.
            </div>
            <div className="">
              This capacity limit is defined based on your subscription plan. Note that you can only use up to the
              specified number of machines at the same time, and if you attempt to use more, you may need to upgrade
              your subscription or wait until a machine becomes available.
            </div>
          </div>
        </div>
      );
    case types.Spendings.GroupType.MachineTime:
      return (
        <div className="f5">
          <div className="mb2">
            <div className="b">What is this?</div>
            <div className="mb2">
              Machine time refers to the time that is spent using Semaphore cloud machines or self-hosted agents.
            </div>
            <div className="">
              You are billed for each minute spent using the machine, and the price varies based on the type of machine
              used. Only the time spent in the &quot;running&quot; state is counted towards your machine time usage.
            </div>
          </div>
        </div>
      );
    case types.Spendings.GroupType.Seat:
      return (
        <div className="f5">
          <div className="mb2">
            <div className="b">What is this?</div>
            <div className="mb2">
              <span className="b">Seats</span> represent the total number of unique users, both members and non-members,
              who have used your Semaphore organization during the billing period.
            </div>
            <div className="mb2">
              <span className="b">Members</span> are users who have been assigned any role in your organization for any
              period during the billing period.
            </div>
            <div className="">
              <span className="b">Non-member</span> users are users who have triggered Semaphore builds through git
              commits but are not assigned any role in your organization.
            </div>
          </div>
        </div>
      );
    case types.Spendings.GroupType.Storage:
      return (
        <div className="f5">
          <div className="mb2">
            <div className="b">What is this?</div>
            <div className="mb2">
              Storage and Egress spending is generated by using{` `}
              <a href="https://docs.semaphoreci.com/essentials/artifacts/" rel="noreferrer" target="_blank">
                artifacts
              </a>
              , which are files generated during your builds.
            </div>
            <div className="mb2">
              Storage is measured in GB per month and increases as you store more data in your artifacts over time.
            </div>
            <div className="">
              Egress is measured in GB and represents the network egress incurred when you download artifacts to an
              external location or within your jobs.
            </div>
          </div>
        </div>
      );
    case types.Spendings.GroupType.Addon:
      return (
        <div className="f5">
          <div className="mb2">
            <div className="b">What is this?</div>
            <div className="mb2">
              Add-ons are additional services that you can purchase to enhance your CI/CD experience in Semaphore.
            </div>
            <div className="">
              Any add-ons enabled have a fixed monthly cost that is added to your spending at the start of each month.
            </div>
          </div>
        </div>
      );
  }
};
