// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.20.0
// source: artifacts.v1.proto

package artifacts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateSignedURLsRequest_Type int32

const (
	GenerateSignedURLsRequest_PUSH      GenerateSignedURLsRequest_Type = 0 // gets signed URLs for Push operation without force
	GenerateSignedURLsRequest_PUSHFORCE GenerateSignedURLsRequest_Type = 1 // gets signed URLs for Push operation with force
	GenerateSignedURLsRequest_PULL      GenerateSignedURLsRequest_Type = 2 // gets signed URLs for Pull operation
	GenerateSignedURLsRequest_YANK      GenerateSignedURLsRequest_Type = 3 // gets signed URLs for Yank operation
)

// Enum value maps for GenerateSignedURLsRequest_Type.
var (
	GenerateSignedURLsRequest_Type_name = map[int32]string{
		0: "PUSH",
		1: "PUSHFORCE",
		2: "PULL",
		3: "YANK",
	}
	GenerateSignedURLsRequest_Type_value = map[string]int32{
		"PUSH":      0,
		"PUSHFORCE": 1,
		"PULL":      2,
		"YANK":      3,
	}
)

func (x GenerateSignedURLsRequest_Type) Enum() *GenerateSignedURLsRequest_Type {
	p := new(GenerateSignedURLsRequest_Type)
	*p = x
	return p
}

func (x GenerateSignedURLsRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerateSignedURLsRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_artifacts_v1_proto_enumTypes[0].Descriptor()
}

func (GenerateSignedURLsRequest_Type) Type() protoreflect.EnumType {
	return &file_artifacts_v1_proto_enumTypes[0]
}

func (x GenerateSignedURLsRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerateSignedURLsRequest_Type.Descriptor instead.
func (GenerateSignedURLsRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_artifacts_v1_proto_rawDescGZIP(), []int{0, 0}
}

type SignedURL_Method int32

const (
	SignedURL_DELETE SignedURL_Method = 0 // deletes storage object or path
	SignedURL_GET    SignedURL_Method = 1 // reads storage object
	SignedURL_HEAD   SignedURL_Method = 2 // queries object or path existance
	SignedURL_PUT    SignedURL_Method = 3 // overwrites storage object
	SignedURL_POST   SignedURL_Method = 4 // concatenates to storage object
)

// Enum value maps for SignedURL_Method.
var (
	SignedURL_Method_name = map[int32]string{
		0: "DELETE",
		1: "GET",
		2: "HEAD",
		3: "PUT",
		4: "POST",
	}
	SignedURL_Method_value = map[string]int32{
		"DELETE": 0,
		"GET":    1,
		"HEAD":   2,
		"PUT":    3,
		"POST":   4,
	}
)

func (x SignedURL_Method) Enum() *SignedURL_Method {
	p := new(SignedURL_Method)
	*p = x
	return p
}

func (x SignedURL_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignedURL_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_artifacts_v1_proto_enumTypes[1].Descriptor()
}

func (SignedURL_Method) Type() protoreflect.EnumType {
	return &file_artifacts_v1_proto_enumTypes[1]
}

func (x SignedURL_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignedURL_Method.Descriptor instead.
func (SignedURL_Method) EnumDescriptor() ([]byte, []int) {
	return file_artifacts_v1_proto_rawDescGZIP(), []int{2, 0}
}

// Request for Generating signed URLs with the given type.
// Contains a list of paths as the Google Cloud Storage destination or source based on the action type.
type GenerateSignedURLsRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Paths         []string                       `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	Type          GenerateSignedURLsRequest_Type `protobuf:"varint,2,opt,name=type,proto3,enum=semaphore.artifacts.v1.GenerateSignedURLsRequest_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSignedURLsRequest) Reset() {
	*x = GenerateSignedURLsRequest{}
	mi := &file_artifacts_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSignedURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignedURLsRequest) ProtoMessage() {}

func (x *GenerateSignedURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignedURLsRequest.ProtoReflect.Descriptor instead.
func (*GenerateSignedURLsRequest) Descriptor() ([]byte, []int) {
	return file_artifacts_v1_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateSignedURLsRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *GenerateSignedURLsRequest) GetType() GenerateSignedURLsRequest_Type {
	if x != nil {
		return x.Type
	}
	return GenerateSignedURLsRequest_PUSH
}

// Response for GenerateSignedURLs
// Contains a list of Signed URLs
type GenerateSignedURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	URLs          []*SignedURL           `protobuf:"bytes,1,rep,name=URLs,proto3" json:"URLs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSignedURLsResponse) Reset() {
	*x = GenerateSignedURLsResponse{}
	mi := &file_artifacts_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSignedURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignedURLsResponse) ProtoMessage() {}

func (x *GenerateSignedURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignedURLsResponse.ProtoReflect.Descriptor instead.
func (*GenerateSignedURLsResponse) Descriptor() ([]byte, []int) {
	return file_artifacts_v1_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateSignedURLsResponse) GetURLs() []*SignedURL {
	if x != nil {
		return x.URLs
	}
	return nil
}

// Contains an URL and its method type
// The path on the GCS can be parsed out of it, so it is not needed
type SignedURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	URL           string                 `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	Method        SignedURL_Method       `protobuf:"varint,2,opt,name=method,proto3,enum=semaphore.artifacts.v1.SignedURL_Method" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedURL) Reset() {
	*x = SignedURL{}
	mi := &file_artifacts_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedURL) ProtoMessage() {}

func (x *SignedURL) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedURL.ProtoReflect.Descriptor instead.
func (*SignedURL) Descriptor() ([]byte, []int) {
	return file_artifacts_v1_proto_rawDescGZIP(), []int{2}
}

func (x *SignedURL) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *SignedURL) GetMethod() SignedURL_Method {
	if x != nil {
		return x.Method
	}
	return SignedURL_DELETE
}

var File_artifacts_v1_proto protoreflect.FileDescriptor

const file_artifacts_v1_proto_rawDesc = "" +
	"\n" +
	"\x12artifacts.v1.proto\x12\x16semaphore.artifacts.v1\"\xb2\x01\n" +
	"\x19GenerateSignedURLsRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12J\n" +
	"\x04type\x18\x02 \x01(\x0e26.semaphore.artifacts.v1.GenerateSignedURLsRequest.TypeR\x04type\"3\n" +
	"\x04Type\x12\b\n" +
	"\x04PUSH\x10\x00\x12\r\n" +
	"\tPUSHFORCE\x10\x01\x12\b\n" +
	"\x04PULL\x10\x02\x12\b\n" +
	"\x04YANK\x10\x03\"S\n" +
	"\x1aGenerateSignedURLsResponse\x125\n" +
	"\x04URLs\x18\x01 \x03(\v2!.semaphore.artifacts.v1.SignedURLR\x04URLs\"\x9b\x01\n" +
	"\tSignedURL\x12\x10\n" +
	"\x03URL\x18\x01 \x01(\tR\x03URL\x12@\n" +
	"\x06method\x18\x02 \x01(\x0e2(.semaphore.artifacts.v1.SignedURL.MethodR\x06method\":\n" +
	"\x06Method\x12\n" +
	"\n" +
	"\x06DELETE\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\b\n" +
	"\x04HEAD\x10\x02\x12\a\n" +
	"\x03PUT\x10\x03\x12\b\n" +
	"\x04POST\x10\x042\x8f\x01\n" +
	"\x10ArtifactsService\x12{\n" +
	"\x12GenerateSignedURLs\x121.semaphore.artifacts.v1.GenerateSignedURLsRequest\x1a2.semaphore.artifacts.v1.GenerateSignedURLsResponseBLZJgithub.com/semaphoreio/semaphore/artifacthub/pkg/api/descriptors/artifactsb\x06proto3"

var (
	file_artifacts_v1_proto_rawDescOnce sync.Once
	file_artifacts_v1_proto_rawDescData []byte
)

func file_artifacts_v1_proto_rawDescGZIP() []byte {
	file_artifacts_v1_proto_rawDescOnce.Do(func() {
		file_artifacts_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifacts_v1_proto_rawDesc), len(file_artifacts_v1_proto_rawDesc)))
	})
	return file_artifacts_v1_proto_rawDescData
}

var file_artifacts_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_artifacts_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_artifacts_v1_proto_goTypes = []any{
	(GenerateSignedURLsRequest_Type)(0), // 0: semaphore.artifacts.v1.GenerateSignedURLsRequest.Type
	(SignedURL_Method)(0),               // 1: semaphore.artifacts.v1.SignedURL.Method
	(*GenerateSignedURLsRequest)(nil),   // 2: semaphore.artifacts.v1.GenerateSignedURLsRequest
	(*GenerateSignedURLsResponse)(nil),  // 3: semaphore.artifacts.v1.GenerateSignedURLsResponse
	(*SignedURL)(nil),                   // 4: semaphore.artifacts.v1.SignedURL
}
var file_artifacts_v1_proto_depIdxs = []int32{
	0, // 0: semaphore.artifacts.v1.GenerateSignedURLsRequest.type:type_name -> semaphore.artifacts.v1.GenerateSignedURLsRequest.Type
	4, // 1: semaphore.artifacts.v1.GenerateSignedURLsResponse.URLs:type_name -> semaphore.artifacts.v1.SignedURL
	1, // 2: semaphore.artifacts.v1.SignedURL.method:type_name -> semaphore.artifacts.v1.SignedURL.Method
	2, // 3: semaphore.artifacts.v1.ArtifactsService.GenerateSignedURLs:input_type -> semaphore.artifacts.v1.GenerateSignedURLsRequest
	3, // 4: semaphore.artifacts.v1.ArtifactsService.GenerateSignedURLs:output_type -> semaphore.artifacts.v1.GenerateSignedURLsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_artifacts_v1_proto_init() }
func file_artifacts_v1_proto_init() {
	if File_artifacts_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifacts_v1_proto_rawDesc), len(file_artifacts_v1_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artifacts_v1_proto_goTypes,
		DependencyIndexes: file_artifacts_v1_proto_depIdxs,
		EnumInfos:         file_artifacts_v1_proto_enumTypes,
		MessageInfos:      file_artifacts_v1_proto_msgTypes,
	}.Build()
	File_artifacts_v1_proto = out.File
	file_artifacts_v1_proto_goTypes = nil
	file_artifacts_v1_proto_depIdxs = nil
}
