version: '3.6'

services:

  app:
    platform: linux/amd64
    build:
      context: .
      cache_from:
        - "${IMAGE:-velocity}:${IMAGE_TAG:-prod}"
      dockerfile: Dockerfile
      target: dev

    tty: true

    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "velocity"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "the-cake-is-a-lie"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"

    links:
      - db:db
      - rabbitmq:rabbitmq

    volumes:
      - .:/app
      - /tmp:/tmp

  db:
    image: postgres:9.6.24
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "the-cake-is-a-lie"
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.9.27-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  repo-data:
    driver: local

  db-data:
    driver: local
