# Local development environment configuration.
# Made originally for GitHub since not everyone is on localhost:3000
# in development. So everyone should create their own github app and
# set the callback.

base_url: "http://id.boxbox.local:3000"

secret_token: "jfieitmv83yfv73osjkdjfvy8213kskjdfo834jv"

github_app_id: "bd59c3a0c448179b5f3f"
github_secret_id: "c40e646d16dca15d4a5155397e4e66b928678f15"
github_app_webhook_secret: "lkasjdlkjKSJHKsa123lskdfn"

bitbucket_app_id: "G3cXBDsDEwVp25rCXL"
bitbucket_secret_id: "LNNfhaLKsfuzjYEeJLkN5Y93cNDb2ej4"

secret_available_only_from_config_file: "test"
