version: '3.6'

services:

  app:
    build:
      context: .
      cache_from:
        - "${REGISTRY_HOST:-local}/branch_hub/${BRANCH:-main}:${IMAGE_TAG:-test}"
      dockerfile: Dockerfile
      target: ${DOCKER_BUILD_TARGET:-dev}
      args:
        - BUILD_ENV=test

    command: "mix run --no-halt"
    ports:
      - "50051:50051"
    tty: true
    volumes:
      - .:/app

    links:
      - db:db

    environment:
      IN_DOCKER: "true"
      POSTGRES_DB_NAME: "front"
      POSTGRES_DB_USER: "postgres"
      POSTGRES_DB_PASSWORD: "the-cake-is-a-lie"
      POSTGRES_DB_HOST: "db"
      POSTGRES_DB_POOL_SIZE: "5"
      AMQP_URL: "amqp://rabbitmq:5672"

  db:
    image: postgres:9.6.0
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "the-cake-is-a-lie"

volumes:
  postgres-data:
    driver: local
