package artifacts

import (
	"context"
	"fmt"
	"path"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"

	artifacthubpb "github.com/semaphoreio/semaphore/mcp_server/pkg/internal_api/artifacthub"
	"github.com/semaphoreio/semaphore/mcp_server/pkg/internalapi"
	"github.com/semaphoreio/semaphore/mcp_server/pkg/tools/internal/shared"
)

type artifactListItem struct {
	Name        string `json:"name"`
	Path        string `json:"path"`
	IsDirectory bool   `json:"isDirectory"`
	Size        int64  `json:"size"`
}

type artifactListPage struct {
	Limit               int    `json:"limit"`
	Returned            int    `json:"returned"`
	Total               int    `json:"total"`
	Truncated           bool   `json:"truncated"`
	PaginationAvailable bool   `json:"paginationAvailable"`
	PaginationNote      string `json:"paginationNote,omitempty"`
}

type artifactListResult struct {
	OrganizationID string             `json:"organizationId"`
	ProjectID      string             `json:"projectId"`
	Scope          string             `json:"scope"`
	ScopeID        string             `json:"scopeId"`
	Path           string             `json:"path"`
	Artifacts      []artifactListItem `json:"artifacts"`
	Page           artifactListPage   `json:"page"`
}

const paginationUnavailableNote = "Pagination beyond the first page is currently unavailable because Artifacthub ListPath requires full directory fetches per request. Narrow path and retry."

func listFullDescription() string {
	return `List artifacts for a project, workflow, or job scope.

Use this tool to:
- Browse artifact directories before downloading files
- Confirm artifact paths for follow-up calls to artifacts_signed_url
- Inspect files generated by project/workflow/job runs

Inputs:
- organization_id (required): Organization UUID context from organizations_list
- scope (required): One of "projects", "workflows", "jobs"
- scope_id (required): UUID for the selected scope
- path (optional): Relative path under the scope root
- project_id (optional): Expected project UUID for additional scope validation
- limit (optional): Number of items to return (default 200, max 1000)

Output:
- artifacts: File and directory entries with relative paths and sizes
- page: Pagination metadata (limit, returned, total, truncated, paginationAvailable, paginationNote)

Note:
- The current Artifacthub ListPath API returns full directory listings.
- This tool returns up to limit entries from the start of that listing.
- If a directory exceeds 5000 entries, the tool aborts and asks you to narrow the path.
- Additional pages are currently unavailable to avoid repeated full-fetch load.

Examples:
1. List root artifacts for a job:
   artifacts_list(organization_id="...", scope="jobs", scope_id="...")

2. List artifacts under a subdirectory:
   artifacts_list(organization_id="...", scope="workflows", scope_id="...", path="test-results")

3. List project artifacts with an explicit limit:
   artifacts_list(organization_id="...", scope="projects", scope_id="...", limit=100)

Typical workflow:
1. Call artifacts_list(...) to discover available paths.
2. Call artifacts_signed_url(...) with the selected path to download the file.`
}

func newListTool(name, description string) mcp.Tool {
	return mcp.NewTool(
		name,
		mcp.WithDescription(description),
		mcp.WithString(
			"organization_id",
			mcp.Required(),
			mcp.Description("Organization UUID context (format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)."),
			mcp.Pattern(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`),
		),
		mcp.WithString(
			"scope",
			mcp.Required(),
			mcp.Description("Artifact scope. Use projects, workflows, or jobs."),
			mcp.Enum(scopeProjects, scopeWorkflows, scopeJobs),
		),
		mcp.WithString(
			"scope_id",
			mcp.Required(),
			mcp.Description("Scope UUID (project/workflow/job ID)."),
			mcp.Pattern(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`),
		),
		mcp.WithString(
			"project_id",
			mcp.Description("Optional project UUID. If provided, it must match the project resolved from scope/scope_id."),
			mcp.Pattern(`^$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`),
		),
		mcp.WithString(
			"path",
			mcp.Description("Optional relative path within the scope root. Do not include a leading slash."),
		),
		mcp.WithNumber(
			"limit",
			mcp.Description("Maximum number of artifacts to return (1-1000)."),
			mcp.Min(1),
			mcp.Max(maxListLimit),
			mcp.DefaultNumber(defaultListLimit),
		),
		mcp.WithReadOnlyHintAnnotation(true),
		mcp.WithIdempotentHintAnnotation(true),
		mcp.WithOpenWorldHintAnnotation(true),
	)
}

func listHandler(api internalapi.Provider) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		orgID, err := requireOrganizationID(req)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		tracker := shared.TrackToolExecution(ctx, listToolName, orgID)
		defer tracker.Cleanup()

		params, err := resolveCommonRequestParams(req, "listing artifacts")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		relativePath, err := sanitizeRelativePath(req.GetString("path", ""), false)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		limit, err := parseLimit(req)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if err := shared.EnsureReadToolsFeature(ctx, api, orgID); err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		access, authErr := resolveArtifactAccess(
			ctx,
			api,
			listToolName,
			params.UserID,
			orgID,
			params.Scope,
			params.ScopeID,
			params.ProvidedProjectID,
			artifactsListPermission,
		)
		if authErr != nil {
			return authErr, nil
		}

		requestPath := artifactPath(params.Scope, params.ScopeID, relativePath)
		items, err := listPath(ctx, api, access.ArtifactStoreID, requestPath)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		artifacts := serializeListItems(items, params.Scope, params.ScopeID)
		if len(artifacts) == 0 && relativePath != "" {
			return mcp.NewToolResultError("Artifact path not found"), nil
		}

		total := len(artifacts)
		if total > maxListItems {
			return mcp.NewToolResultError(
				fmt.Sprintf("Artifact directory listing contains %d entries, which exceeds the safe client-side paging limit of %d. Narrow the path and retry.", total, maxListItems),
			), nil
		}
		start := 0
		if start > total {
			start = total
		}
		end := start + limit
		if end > total {
			end = total
		}
		pagedArtifacts := artifacts[start:end]
		truncated := end < total

		result := artifactListResult{
			OrganizationID: orgID,
			ProjectID:      access.ProjectID,
			Scope:          params.Scope,
			ScopeID:        params.ScopeID,
			Path:           relativePath,
			Artifacts:      pagedArtifacts,
			Page: artifactListPage{
				Limit:               limit,
				Returned:            len(pagedArtifacts),
				Total:               total,
				Truncated:           truncated,
				PaginationAvailable: false,
				PaginationNote:      paginationUnavailableNote,
			},
		}

		markdown := formatListMarkdown(result)
		markdown = shared.TruncateResponse(markdown, shared.MaxResponseChars)

		tracker.MarkSuccess()
		return &mcp.CallToolResult{
			Content:           []mcp.Content{mcp.NewTextContent(markdown)},
			StructuredContent: result,
		}, nil
	}
}

func serializeListItems(items []*artifacthubpb.ListItem, scope, scopeID string) []artifactListItem {
	result := make([]artifactListItem, 0, len(items))
	for _, item := range items {
		if item == nil {
			continue
		}

		relative := strings.Trim(toRelativeArtifactPath(item.GetName(), scope, scopeID), "/")
		if relative == "" {
			continue
		}

		name := path.Base(relative)
		if name == "." {
			name = relative
		}

		result = append(result, artifactListItem{
			Name:        name,
			Path:        relative,
			IsDirectory: item.GetIsDirectory(),
			Size:        item.GetSize(),
		})
	}
	return result
}

func formatListMarkdown(result artifactListResult) string {
	mb := shared.NewMarkdownBuilder()

	mb.H1(fmt.Sprintf("Artifacts (%d returned)", result.Page.Returned))
	mb.KeyValue("Organization ID", fmt.Sprintf("`%s`", result.OrganizationID))
	mb.KeyValue("Project ID", fmt.Sprintf("`%s`", result.ProjectID))
	mb.KeyValue("Scope", fmt.Sprintf("%s (`%s`)", result.Scope, result.ScopeID))
	if result.Path != "" {
		mb.KeyValue("Path", fmt.Sprintf("`%s`", result.Path))
	}
	mb.KeyValue(
		"Page",
		fmt.Sprintf("limit=%d, returned=%d, total=%d, truncated=%t, paginationAvailable=%t",
			result.Page.Limit,
			result.Page.Returned,
			result.Page.Total,
			result.Page.Truncated,
			result.Page.PaginationAvailable,
		),
	)
	if result.Page.PaginationNote != "" {
		mb.KeyValue("Pagination Note", result.Page.PaginationNote)
	}

	if len(result.Artifacts) == 0 {
		mb.Line()
		mb.Paragraph("No artifacts found for the requested scope/path.")
		return mb.String()
	}

	mb.Line()
	mb.H2("Entries")
	for _, item := range result.Artifacts {
		entryType := "FILE"
		if item.IsDirectory {
			entryType = "DIR"
		}
		mb.ListItem(fmt.Sprintf("[%s] `%s` (%s, %d bytes)", entryType, item.Path, item.Name, item.Size))
	}

	return mb.String()
}
